apiVersion: v1
kind: Service
metadata:
  name: vaeloom-document-ingestion
  namespace: vaeloom
  labels:
    app.kubernetes.io/name: document-ingestion
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 3110
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: document-ingestion
