apiVersion: v1
kind: Service
metadata:
  name: vaeloom-job-scheduler
  namespace: vaeloom
  labels:
    app.kubernetes.io/name: job-scheduler
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 3140
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: job-scheduler
