apiVersion: v1
kind: Service
metadata:
  name: vaeloom-temporal
  namespace: vaeloom
  labels:
    app.kubernetes.io/name: temporal
spec:
  selector:
    app.kubernetes.io/name: temporal
  ports:
    - name: grpc
      port: 7233
      targetPort: 7233
      protocol: TCP
    - name: frontend
      port: 8233
      targetPort: 8233
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-db
  namespace: vaeloom
spec:
  selector:
    app: temporal-db-external
  ports:
    - port: 5432
      targetPort: 5432
  type: ExternalName
  externalName: vaeloom-prod-postgres.xxxxxx.us-east-1.rds.amazonaws.com
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-visibility-db
  namespace: vaeloom
spec:
  selector:
    app: temporal-visibility-db-external
  ports:
    - port: 5432
      targetPort: 5432
  type: ExternalName
  externalName: vaeloom-prod-postgres-visibility.xxxxxx.us-east-1.rds.amazonaws.com
---
apiVersion: v1
kind: Service
metadata:
  name: vaeloom-temporal-worker
  namespace: vaeloom
  labels:
    app.kubernetes.io/name: temporal-worker
spec:
  selector:
    app.kubernetes.io/name: temporal-worker
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
  type: ClusterIP
