/**
 * Design token source of record.
 *
 * THIS JSON TREE IS NOT THE RUNTIME AUTHORITY. The stylesheet that actually
 * drives the application is `apps/web/src/styles/globals.css`; the app build
 * never imports these files, and `generateCssVariables()` has no callers in the
 * app. Editing a value here changes nothing at runtime.
 *
 * Treat this module as documentation and tooling input only. Do not add code
 * paths, styles, or Tailwind config that assume these values reach the DOM, and
 * do not "fix" a visual regression by editing here — change globals.css.
 *
 * The two engines are not aligned. Measured against the current
 * `apps/web/src/styles/globals.css` (86 unique custom properties):
 *
 *   - Colour: disjoint. Of the 57 `--color-*` names here, exactly two exist
 *     there — `--color-focus-ring` and `--color-focus-ring-offset` — and those
 *     two are value-identical in the dark and light themes. globals.css uses
 *     its own unprefixed palette (`--surface`, `--text`, `--accent`, ...).
 *   - Radius + elevation: aligned. All 17 `--radius-*` / `--elevation-*` names
 *     exist in both and are value-identical.
 *   - Space + typography: engine-only. globals.css defines no `--space-*`,
 *     `--font-size-*` or `--font-weight-*`.
 *
 * `src/__tests__/tokens.test.ts` pins all three facts as a baseline so the drift
 * cannot change silently.
 */
import component from './component.json';
import primitives from './primitives.json';
import semantic from './semantic.json';
import darkTheme from './themes/dark.json';
import highContrastTheme from './themes/high-contrast.json';
import lightTheme from './themes/light.json';

/**
 * Machine-readable form of the warning above, for consumers that want to assert
 * on it rather than read a comment.
 */
export const TOKEN_SOURCE_OF_TRUTH = {
  runtime: 'apps/web/src/styles/globals.css',
  designRecord: 'packages/ui-kit/src/tokens',
  wiredIntoAppBuild: false,
  sharedColorNames: ['--color-focus-ring', '--color-focus-ring-offset'],
  sharedScaleNames: 17,
  engineOnlyNamespaces: ['--space-*', '--font-size-*', '--font-weight-*'],
} as const;

export const tokens = {
  primitives,
  semantic,
  component,
  themes: {
    dark: darkTheme,
    light: lightTheme,
    'high-contrast': highContrastTheme,
  },
} as const;

export type ThemeName = 'dark' | 'light' | 'high-contrast';
export type Primitives = typeof primitives;
export type SemanticTokens = typeof semantic;
export type ComponentTokens = typeof component;

/**
 * Validates that all required theme variables are defined across all themes.
 * Returns true if valid, throws error if any theme is incomplete.
 */
export function validateTokens(): { valid: boolean; errors: string[] } {
  const errors: string[] = [];
  const requiredKeys = Object.keys(darkTheme.values);

  const themeList: Array<{ name: string; values: Record<string, string> }> = [
    { name: 'dark', values: darkTheme.values },
    { name: 'light', values: lightTheme.values },
    { name: 'high-contrast', values: highContrastTheme.values },
  ];

  for (const theme of themeList) {
    for (const key of requiredKeys) {
      if (!theme.values[key]) {
        errors.push(`Theme '${theme.name}' is missing required token: ${key}`);
      }
    }
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}

/**
 * Generate CSS variable declarations for inclusion in stylesheets.
 *
 * Not called by the app — see the module docstring. The font scale is emitted
 * because `component.json` already dereferences `--font-size-*`; font *family*
 * is deliberately omitted because those values dereference `--font-*` custom
 * properties owned by the app's font loader, not by this engine.
 */
export function generateCssVariables(): string {
  function formatVars(values: Record<string, string>): string {
    return Object.entries(values)
      .map(([key, val]) => `  ${key}: ${val};`)
      .join('\n');
  }

  const radiusVars = Object.entries(primitives.radius)
    .map(([key, val]) => `  --radius-${key}: ${val};`)
    .join('\n');

  const elevationVars = Object.entries(primitives.elevation)
    .map(([key, val]) => `  --elevation-${key}: ${val};`)
    .join('\n');

  const spaceVars = Object.entries(primitives.space)
    .map(([key, val]) => `  --space-${key}: ${val};`)
    .join('\n');

  const fontSizeVars = Object.entries(primitives.typography.fontSize)
    .flatMap(([key, val]) => [
      `  --font-size-${key}: ${val.size};`,
      `  --line-height-${key}: ${val.lineHeight};`,
    ])
    .join('\n');

  const fontWeightVars = Object.entries(primitives.typography.fontWeight)
    .map(([key, val]) => `  --font-weight-${key}: ${val};`)
    .join('\n');

  return `
/* Generated by Vaeloom Design Token Engine */
:root {
  /* Radius Primitives & Semantics */
${radiusVars}
  --radius-control: var(--radius-md);
  --radius-card: var(--radius-lg);
  --radius-container: var(--radius-xl);
  --radius-pill: var(--radius-full);

  /* Elevation Primitives & Semantics */
${elevationVars}
  --elevation-card: var(--elevation-raised);

  /* Space Primitives */
${spaceVars}

  /* Typography Primitives (font families are app-owned, see docstring) */
${fontSizeVars}
${fontWeightVars}
}

:root,
.dark {
${formatVars(darkTheme.values)}
}

.light {
${formatVars(lightTheme.values)}
}

.high-contrast,
[data-theme="high-contrast"] {
${formatVars(highContrastTheme.values)}
  --color-border-default: #ffffff;
  --color-border-strong: #ffffff;
  --color-border-focus: #ffff00;
  --color-focus-ring: #ffff00;
}

@media (prefers-contrast: more) {
  :root {
${formatVars(highContrastTheme.values)}
    --color-border-default: #ffffff;
    --color-border-strong: #ffffff;
    --color-border-focus: #ffff00;
    --color-focus-ring: #ffff00;
  }
}
`.trim();
}
