import primitives from './primitives.json';
import semantic from './semantic.json';
import component from './component.json';
import darkTheme from './themes/dark.json';
import lightTheme from './themes/light.json';
import highContrastTheme from './themes/high-contrast.json';

export const tokens = {
  primitives,
  semantic,
  component,
  themes: {
    dark: darkTheme,
    light: lightTheme,
    'high-contrast': highContrastTheme,
  },
} as const;

export type ThemeName = 'dark' | 'light' | 'high-contrast';
export type Primitives = typeof primitives;
export type SemanticTokens = typeof semantic;
export type ComponentTokens = typeof component;

/**
 * Validates that all required theme variables are defined across all themes.
 * Returns true if valid, throws error if any theme is incomplete.
 */
export function validateTokens(): { valid: boolean; errors: string[] } {
  const errors: string[] = [];
  const requiredKeys = Object.keys(darkTheme.values);

  const themeList: Array<{ name: string; values: Record<string, string> }> = [
    { name: 'dark', values: darkTheme.values },
    { name: 'light', values: lightTheme.values },
    { name: 'high-contrast', values: highContrastTheme.values },
  ];

  for (const theme of themeList) {
    for (const key of requiredKeys) {
      if (!theme.values[key]) {
        errors.push(`Theme '${theme.name}' is missing required token: ${key}`);
      }
    }
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}

/**
 * Generate CSS variable declarations for inclusion in stylesheets.
 */
export function generateCssVariables(): string {
  function formatVars(values: Record<string, string>): string {
    return Object.entries(values)
      .map(([key, val]) => `  ${key}: ${val};`)
      .join('\n');
  }

  const radiusVars = Object.entries(primitives.radius)
    .map(([key, val]) => `  --radius-${key}: ${val};`)
    .join('\n');

  const elevationVars = Object.entries(primitives.elevation)
    .map(([key, val]) => `  --elevation-${key}: ${val};`)
    .join('\n');

  const spaceVars = Object.entries(primitives.space)
    .map(([key, val]) => `  --space-${key}: ${val};`)
    .join('\n');

  return `
/* Generated by Vaeloom Design Token Engine */
:root {
  /* Radius Primitives & Semantics */
${radiusVars}
  --radius-control: var(--radius-md);
  --radius-card: var(--radius-lg);
  --radius-container: var(--radius-xl);
  --radius-pill: var(--radius-full);

  /* Elevation Primitives & Semantics */
${elevationVars}
  --elevation-card: var(--elevation-raised);

  /* Space Primitives */
${spaceVars}
}

:root,
.dark {
${formatVars(darkTheme.values)}
}

.light {
${formatVars(lightTheme.values)}
}

.high-contrast,
[data-theme="high-contrast"] {
${formatVars(highContrastTheme.values)}
  --color-border-default: #ffffff;
  --color-border-strong: #ffffff;
  --color-border-focus: #ffff00;
  --color-focus-ring: #ffff00;
}

@media (prefers-contrast: more) {
  :root {
${formatVars(highContrastTheme.values)}
    --color-border-default: #ffffff;
    --color-border-strong: #ffffff;
    --color-border-focus: #ffff00;
    --color-focus-ring: #ffff00;
  }
}
`.trim();
}
