import primitives from './primitives.json';
import semantic from './semantic.json';
import component from './component.json';
import darkTheme from './themes/dark.json';
import lightTheme from './themes/light.json';
import highContrastTheme from './themes/high-contrast.json';

export const tokens = {
  primitives,
  semantic,
  component,
  themes: {
    dark: darkTheme,
    light: lightTheme,
    'high-contrast': highContrastTheme,
  },
} as const;

export type ThemeName = 'dark' | 'light' | 'high-contrast';
export type Primitives = typeof primitives;
export type SemanticTokens = typeof semantic;
export type ComponentTokens = typeof component;

/**
 * Validates that all required theme variables are defined across all themes.
 * Returns true if valid, throws error if any theme is incomplete.
 */
export function validateTokens(): { valid: boolean; errors: string[] } {
  const errors: string[] = [];
  const requiredKeys = Object.keys(darkTheme.values);

  const themeList: Array<{ name: string; values: Record<string, string> }> = [
    { name: 'dark', values: darkTheme.values },
    { name: 'light', values: lightTheme.values },
    { name: 'high-contrast', values: highContrastTheme.values },
  ];

  for (const theme of themeList) {
    for (const key of requiredKeys) {
      if (!theme.values[key]) {
        errors.push(`Theme '${theme.name}' is missing required token: ${key}`);
      }
    }
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}

/**
 * Generate CSS variable declarations for inclusion in stylesheets.
 */
export function generateCssVariables(): string {
  function formatVars(values: Record<string, string>): string {
    return Object.entries(values)
      .map(([key, val]) => `  ${key}: ${val};`)
      .join('\n');
  }

  return `
/* Generated by Vaeloom Design Token Engine */
:root,
.dark {
${formatVars(darkTheme.values)}
}

.light {
${formatVars(lightTheme.values)}
}

.high-contrast {
${formatVars(highContrastTheme.values)}
}
`.trim();
}
