"""Enterprise Composio App Catalog (350+ Integrations).

Provides comprehensive metadata for official Composio SaaS integrations,
categorized into Vaeloom's 5 Enterprise Tiers:
1. Career & ATS
2. Startup & Business
3. Productivity & Study
4. Engineering & Cloud
5. Communication & Community
"""

from typing import Any

COMPOSIO_SUPPORTED_APPS: list[dict[str, Any]] = [
    # ──────────────────────────────────────────────────────────────────────────
    # 1. CAREER & ATS (64 apps)
    # ──────────────────────────────────────────────────────────────────────────
    {"id": "greenhouse", "name": "Greenhouse ATS", "category": "Career & ATS", "description": "Candidate pipeline stages, scorecards, job postings, and interview schedules", "action_count": 54},
    {"id": "lever", "name": "Lever ATS", "category": "Career & ATS", "description": "Applicant tracking, candidate sourcing, requisition approvals, and interviews", "action_count": 48},
    {"id": "ashby", "name": "Ashby ATS", "category": "Career & ATS", "description": "Modern all-in-one recruiting platform with structured candidate interviews and analytics", "action_count": 44},
    {"id": "workday", "name": "Workday", "category": "Career & ATS", "description": "Enterprise human capital management, organizational hierarchies, and payroll", "action_count": 58},
    {"id": "github", "name": "GitHub", "category": "Career & ATS", "description": "Developer portfolio, public receipts, commit proof, and repository collaboration", "action_count": 82},
    {"id": "gitlab", "name": "GitLab", "category": "Career & ATS", "description": "Open-source contributions, engineering portfolio, and code merge proofs", "action_count": 68},
    {"id": "linkedin", "name": "LinkedIn", "category": "Career & ATS", "description": "Professional network profile, career recommendations, and talent search", "action_count": 42},
    {"id": "substack", "name": "Substack", "category": "Career & ATS", "description": "Engineering newsletters, thought leadership publications, and audience subscribers", "action_count": 24},
    {"id": "taleo", "name": "Oracle Taleo", "category": "Career & ATS", "description": "Enterprise talent acquisition, candidate onboarding, and compliance screening", "action_count": 36},
    {"id": "bamboohr", "name": "BambooHR", "category": "Career & ATS", "description": "Employee directory, time-off requests, onboarding packets, and performance reviews", "action_count": 42},
    {"id": "rippling", "name": "Rippling", "category": "Career & ATS", "description": "Unified workforce platform managing HR, employee IT devices, and payroll", "action_count": 48},
    {"id": "remote-com", "name": "Remote.com", "category": "Career & ATS", "description": "Global employer of record, international compliance, payroll, and benefits", "action_count": 36},
    {"id": "deel", "name": "Deel", "category": "Career & ATS", "description": "Global contractor hiring, compliance contracts, payroll, and tax forms", "action_count": 46},
    {"id": "workable", "name": "Workable", "category": "Career & ATS", "description": "Job board syndication, AI candidate screening, and candidate communication", "action_count": 38},
    {"id": "recruitee", "name": "Recruitee", "category": "Career & ATS", "description": "Collaborative hiring platform, candidate pipelines, and automated recruiting emails", "action_count": 32},
    {"id": "breezyhr", "name": "Breezy HR", "category": "Career & ATS", "description": "Visual candidate recruiting pipelines, video interviews, and team scorecards", "action_count": 30},
    {"id": "jazzhr", "name": "JazzHR", "category": "Career & ATS", "description": "Affordable applicant tracking system for fast-growing businesses", "action_count": 28},
    {"id": "smartrecruiters", "name": "SmartRecruiters", "category": "Career & ATS", "description": "Enterprise talent acquisition suite, CRM candidate sourcing, and offer management", "action_count": 45},
    {"id": "jobvite", "name": "Jobvite", "category": "Career & ATS", "description": "End-to-end recruitment marketing, applicant tracking, and employee onboarding", "action_count": 35},
    {"id": "bullhorn", "name": "Bullhorn CRM", "category": "Career & ATS", "description": "Staffing and recruiting CRM, candidate resume parsing, and placement tracking", "action_count": 40},
    {"id": "personio", "name": "Personio", "category": "Career & ATS", "description": "European HR software for small and medium-sized enterprises and recruiting", "action_count": 38},
    {"id": "hibob", "name": "HiBob (Bob)", "category": "Career & ATS", "description": "Modern HR platform for dynamic workplace culture and people management", "action_count": 34},
    {"id": "lattice", "name": "Lattice", "category": "Career & ATS", "description": "Employee performance management, 1-on-1 agendas, OKRs, and employee engagement", "action_count": 32},
    {"id": "culture-amp", "name": "Culture Amp", "category": "Career & ATS", "description": "Employee engagement surveys, performance reviews, and people analytics", "action_count": 26},
    {"id": "gem", "name": "Gem", "category": "Career & ATS", "description": "Talent engagement, sourcing sequences, talent CRM, and pipeline analytics", "action_count": 30},
    {"id": "checkr", "name": "Checkr", "category": "Career & ATS", "description": "Automated background check screening, identity verification, and compliance", "action_count": 24},
    {"id": "seekout", "name": "SeekOut", "category": "Career & ATS", "description": "AI-powered talent search, diversity sourcing, and candidate contact enrichment", "action_count": 26},
    {"id": "15five", "name": "15Five", "category": "Career & ATS", "description": "Continuous performance management, weekly check-ins, and high performance culture", "action_count": 22},
    {"id": "leapsome", "name": "Leapsome", "category": "Career & ATS", "description": "People enablement platform for continuous feedback, goal setting, and appraisals", "action_count": 24},
    {"id": "charthop", "name": "ChartHop", "category": "Career & ATS", "description": "People analytics, headcount planning, compensation reviews, and org charting", "action_count": 28},
    {"id": "factorial", "name": "Factorial HR", "category": "Career & ATS", "description": "All-in-one HR software for time tracking, document management, and payroll", "action_count": 26},
    {"id": "teamtailor", "name": "Teamtailor", "category": "Career & ATS", "description": "Modern ATS with career site building, candidate NPS, and candidate nurture", "action_count": 32},
    {"id": "pinpointhq", "name": "Pinpoint ATS", "category": "Career & ATS", "description": "Intelligent talent acquisition software designed to attract top candidates", "action_count": 25},
    {"id": "hireology", "name": "Hireology", "category": "Career & ATS", "description": "Recruitment CRM and candidate verification for multi-location businesses", "action_count": 22},
    {"id": "fountain", "name": "Fountain", "category": "Career & ATS", "description": "High-volume frontline workforce hiring and applicant workflow automation", "action_count": 28},
    {"id": "comeet", "name": "Comeet ATS", "category": "Career & ATS", "description": "Collaborative recruitment platform with integrated sourcing and screening", "action_count": 24},
    {"id": "eightfold", "name": "Eightfold AI", "category": "Career & ATS", "description": "AI talent intelligence platform for deep skills matching and career progression", "action_count": 30},
    {"id": "phenom", "name": "Phenom People", "category": "Career & ATS", "description": "Talent experience platform unifying candidate, recruiter, and employee journeys", "action_count": 32},
    {"id": "beamery", "name": "Beamery", "category": "Career & ATS", "description": "Talent lifecycle management and enterprise skills taxonomy intelligence", "action_count": 28},
    {"id": "textio", "name": "Textio", "category": "Career & ATS", "description": "Augmented writing guidance for bias-free job descriptions and performance evaluations", "action_count": 20},
    {"id": "hackerearth", "name": "HackerEarth", "category": "Career & ATS", "description": "Technical coding assessments, hackathons, and remote interview environments", "action_count": 26},
    {"id": "hackerrank", "name": "HackerRank", "category": "Career & ATS", "description": "Developer skills evaluation, structured technical interviews, and benchmark ranking", "action_count": 32},
    {"id": "codesignal", "name": "CodeSignal", "category": "Career & ATS", "description": "Objective technical talent assessment and coding score certification", "action_count": 28},
    {"id": "codility", "name": "Codility", "category": "Career & ATS", "description": "Online code tests, candidate evaluations, and live technical pair-programming", "action_count": 26},
    {"id": "testgorilla", "name": "TestGorilla", "category": "Career & ATS", "description": "Pre-employment skills testing library covering cognitive ability and software skills", "action_count": 24},
    {"id": "criteria-corp", "name": "Criteria Corp", "category": "Career & ATS", "description": "Scientifically validated candidate aptitude, personality, and skills assessments", "action_count": 22},
    {"id": "hirevue", "name": "HireVue", "category": "Career & ATS", "description": "Video interviewing, conversational AI candidate scheduling, and skill evaluations", "action_count": 26},
    {"id": "modern-hire", "name": "Modern Hire", "category": "Career & ATS", "description": "Enterprise hiring platform providing automated interviewing and candidate science", "action_count": 24},
    {"id": "vervoe", "name": "Vervoe", "category": "Career & ATS", "description": "Skills-based candidate evaluation tests tailored to real-world job responsibilities", "action_count": 22},
    {"id": "indeed", "name": "Indeed", "category": "Career & ATS", "description": "World-wide job posting syndication, resume search, and candidate applications", "action_count": 36},
    {"id": "ziprecruiter", "name": "ZipRecruiter", "category": "Career & ATS", "description": "Smart matching candidate syndication and immediate employer interview invites", "action_count": 30},
    {"id": "glassdoor", "name": "Glassdoor", "category": "Career & ATS", "description": "Company reviews, salary benchmarks, and interview experience intelligence", "action_count": 25},
    {"id": "wellfound", "name": "Wellfound (AngelList)", "category": "Career & ATS", "description": "Startup job marketplace connecting high-growth venture companies and builders", "action_count": 34},
    {"id": "handshake", "name": "Handshake", "category": "Career & ATS", "description": "Early-career talent portal connecting university students with employers", "action_count": 28},
    {"id": "monster", "name": "Monster Jobs", "category": "Career & ATS", "description": "Global career portal for applicant discovery and candidate resume indexing", "action_count": 24},
    {"id": "careerbuilder", "name": "CareerBuilder", "category": "Career & ATS", "description": "Talent acquisition network and employment advertising services", "action_count": 22},
    {"id": "dice", "name": "Dice Tech Careers", "category": "Career & ATS", "description": "Specialized technology careers job network and recruiter sourcing", "action_count": 26},
    {"id": "upwork", "name": "Upwork", "category": "Career & ATS", "description": "Freelance marketplace, verified client contracts, job proposals, and work earnings", "action_count": 38},
    {"id": "fiverr", "name": "Fiverr", "category": "Career & ATS", "description": "Service catalog gigs, client orders, and portfolio gig deliveries", "action_count": 30},
    {"id": "toptal", "name": "Toptal", "category": "Career & ATS", "description": "Elite network of top freelance software engineers, designers, and finance experts", "action_count": 24},
    {"id": "turing", "name": "Turing", "category": "Career & ATS", "description": "AI-powered talent cloud vetting and matching global remote software developers", "action_count": 22},
    {"id": "contra", "name": "Contra", "category": "Career & ATS", "description": "Commission-free freelance portfolio, verified recommendations, and client contracts", "action_count": 25},
    {"id": "readcv", "name": "ReadCV", "category": "Career & ATS", "description": "Modern design-centric professional profile and career timeline networking", "action_count": 18},
    {"id": "peerlist", "name": "Peerlist", "category": "Career & ATS", "description": "Proof-of-work professional community showcasing GitHub commits and live side-projects", "action_count": 20},

    # ──────────────────────────────────────────────────────────────────────────
    # 2. STARTUP & BUSINESS (66 apps)
    # ──────────────────────────────────────────────────────────────────────────
    {"id": "stripe", "name": "Stripe", "category": "Startup & Business", "description": "Process payments, manage customer subscriptions, query invoices, and balance ledgers", "action_count": 68},
    {"id": "mercury", "name": "Mercury Bank", "category": "Startup & Business", "description": "Tech banking platform, wire transfers, transaction search, and account balances", "action_count": 28},
    {"id": "brex", "name": "Brex", "category": "Startup & Business", "description": "Corporate credit cards, spend management, expense approvals, and budget tracking", "action_count": 32},
    {"id": "ramp", "name": "Ramp", "category": "Startup & Business", "description": "Corporate card spend controls, automated receipt matching, and vendor savings", "action_count": 34},
    {"id": "hubspot", "name": "HubSpot", "category": "Startup & Business", "description": "CRM contacts, deal stages, company profiles, and marketing lead automation", "action_count": 76},
    {"id": "salesforce", "name": "Salesforce", "category": "Startup & Business", "description": "Enterprise customer 360, lead pipelines, opportunities, and SOQL queries", "action_count": 84},
    {"id": "linear", "name": "Linear", "category": "Startup & Business", "description": "Product issue tracking, cycle management, and roadmap synchronization", "action_count": 54},
    {"id": "apollo", "name": "Apollo.io", "category": "Startup & Business", "description": "B2B lead intelligence, executive contact enrichment, and sales sequencing", "action_count": 48},
    {"id": "paypal", "name": "PayPal", "category": "Startup & Business", "description": "Online payment gateway, merchant invoicing, and transaction status queries", "action_count": 38},
    {"id": "square", "name": "Square", "category": "Startup & Business", "description": "Point-of-sale payments, merchant orders, customer records, and inventory", "action_count": 42},
    {"id": "quickbooks", "name": "QuickBooks Online", "category": "Startup & Business", "description": "Enterprise bookkeeping, chart of accounts, expense reports, and tax ledgers", "action_count": 54},
    {"id": "xero", "name": "Xero", "category": "Startup & Business", "description": "Small business cloud accounting, bank feeds, reconciliation, and invoicing", "action_count": 48},
    {"id": "shopify", "name": "Shopify", "category": "Startup & Business", "description": "E-commerce catalog management, customer orders, shipping labels, and inventory", "action_count": 65},
    {"id": "chargebee", "name": "Chargebee", "category": "Startup & Business", "description": "Subscription billing automation, revenue recognition, and churn analytics", "action_count": 44},
    {"id": "recurly", "name": "Recurly", "category": "Startup & Business", "description": "Recurring billing engine, payment optimization, and subscription lifecycle management", "action_count": 36},
    {"id": "gusto", "name": "Gusto", "category": "Startup & Business", "description": "Automated payroll processing, employee benefits, and contractor payments", "action_count": 42},
    {"id": "wave", "name": "Wave Accounting", "category": "Startup & Business", "description": "Free invoicing, receipt scanning, and simple accounting for freelancers", "action_count": 24},
    {"id": "freshbooks", "name": "FreshBooks", "category": "Startup & Business", "description": "Cloud accounting software for client invoicing, time tracking, and expenses", "action_count": 36},
    {"id": "bill", "name": "Bill.com", "category": "Startup & Business", "description": "Accounts payable and receivable automation with multi-level approval workflows", "action_count": 38},
    {"id": "expensify", "name": "Expensify", "category": "Startup & Business", "description": "Automated expense report receipt scanning and corporate reimbursement", "action_count": 30},
    {"id": "wise", "name": "Wise (TransferWise)", "category": "Startup & Business", "description": "International multi-currency bank transfers, currency exchange, and balance queries", "action_count": 32},
    {"id": "paddle", "name": "Paddle", "category": "Startup & Business", "description": "Merchant of record for SaaS software sales, global tax compliance, and billing", "action_count": 36},
    {"id": "lemon-squeezy", "name": "Lemon Squeezy", "category": "Startup & Business", "description": "Payments, tax, and subscriptions for digital products and SaaS software", "action_count": 30},
    {"id": "plaid", "name": "Plaid", "category": "Startup & Business", "description": "Connect user bank accounts, verify account balances, and fetch transaction history", "action_count": 35},
    {"id": "netsuite", "name": "Oracle NetSuite", "category": "Startup & Business", "description": "Enterprise cloud ERP system, financial consolidation, and inventory control", "action_count": 60},
    {"id": "pipedrive", "name": "Pipedrive", "category": "Startup & Business", "description": "Visual pipeline sales CRM for managing activity and closing deals", "action_count": 52},
    {"id": "zoho-crm", "name": "Zoho CRM", "category": "Startup & Business", "description": "Lead scoring, deal progression, and sales automation for global teams", "action_count": 58},
    {"id": "close", "name": "Close CRM", "category": "Startup & Business", "description": "Inside sales CRM with built-in calling, SMS, and email sequencing", "action_count": 46},
    {"id": "attio", "name": "Attio", "category": "Startup & Business", "description": "Next-generation relational CRM built with real-time data sync and custom objects", "action_count": 40},
    {"id": "gong", "name": "Gong.io", "category": "Startup & Business", "description": "Revenue intelligence platform analyzing sales calls, deals, and customer sentiment", "action_count": 38},
    {"id": "outreach", "name": "Outreach", "category": "Startup & Business", "description": "Sales engagement platform, automated prospect sequences, and pipeline tracking", "action_count": 48},
    {"id": "clay", "name": "Clay", "category": "Startup & Business", "description": "Programmatic outbound prospecting, waterfall data enrichment, and AI scoring", "action_count": 36},
    {"id": "salesloft", "name": "Salesloft", "category": "Startup & Business", "description": "Sales execution platform for managing customer cadences and opportunity forecasting", "action_count": 42},
    {"id": "lemlist", "name": "Lemlist", "category": "Startup & Business", "description": "Personalized cold email outreach with dynamic image and video personalization", "action_count": 32},
    {"id": "instantly", "name": "Instantly.ai", "category": "Startup & Business", "description": "Unlimited email warm-up, deliverability network, and bulk cold outreach", "action_count": 30},
    {"id": "woodpecker", "name": "Woodpecker", "category": "Startup & Business", "description": "Automated cold email outreach with human-like sending rhythms", "action_count": 26},
    {"id": "phantombuster", "name": "PhantomBuster", "category": "Startup & Business", "description": "Automated lead generation, LinkedIn profile scrapers, and web data extraction", "action_count": 32},
    {"id": "lusha", "name": "Lusha", "category": "Startup & Business", "description": "Direct phone numbers, corporate email addresses, and company firmographics", "action_count": 25},
    {"id": "hunter", "name": "Hunter.io", "category": "Startup & Business", "description": "Find and verify professional email addresses by company domain name", "action_count": 28},
    {"id": "clearbit", "name": "Clearbit", "category": "Startup & Business", "description": "Real-time B2B company enrichment, website IP deanonymization, and lead scoring", "action_count": 36},
    {"id": "zoominfo", "name": "ZoomInfo", "category": "Startup & Business", "description": "Comprehensive B2B company intelligence, org charts, and executive contact data", "action_count": 42},
    {"id": "cognism", "name": "Cognism", "category": "Startup & Business", "description": "GDPR-compliant global B2B phone and email contact data", "action_count": 30},
    {"id": "freshsales", "name": "Freshsales", "category": "Startup & Business", "description": "AI-powered sales CRM with built-in phone, email, and activity tracking", "action_count": 38},
    {"id": "copper", "name": "Copper CRM", "category": "Startup & Business", "description": "Google Workspace-native CRM for managing customer relationships in Gmail", "action_count": 34},
    {"id": "insightly", "name": "Insightly", "category": "Startup & Business", "description": "Combined CRM and project management for growing businesses", "action_count": 36},
    {"id": "demandbase", "name": "Demandbase", "category": "Startup & Business", "description": "Account-based marketing (ABM), intent data, and B2B ad targeting", "action_count": 28},
    {"id": "6sense", "name": "6sense", "category": "Startup & Business", "description": "Predictive account intent and buyer journey intelligence platform", "action_count": 26},
    {"id": "folk", "name": "Folk CRM", "category": "Startup & Business", "description": "All-in-one CRM for managing candidate, investor, and client relationships", "action_count": 28},
    {"id": "highspot", "name": "Highspot", "category": "Startup & Business", "description": "Sales enablement platform connecting content, guidance, and pitch analytics", "action_count": 30},
    {"id": "seismic", "name": "Seismic", "category": "Startup & Business", "description": "Global leader in sales enablement, automated content personalization, and training", "action_count": 34},
    {"id": "carta", "name": "Carta", "category": "Startup & Business", "description": "Equity management, 409A valuations, cap tables, and investor relations", "action_count": 32},
    {"id": "pulley", "name": "Pulley", "category": "Startup & Business", "description": "Cap table management, equity grants, option exercises, and dilution modeling", "action_count": 26},
    {"id": "angellist", "name": "AngelList Venture", "category": "Startup & Business", "description": "Venture funds, syndicates, rolling funds, and startup investor onboarding", "action_count": 28},
    {"id": "pitchbook", "name": "PitchBook", "category": "Startup & Business", "description": "Private capital market data, venture rounds, private equity, and M&A intelligence", "action_count": 32},
    {"id": "crunchbase", "name": "Crunchbase", "category": "Startup & Business", "description": "Startup funding rounds, investor portfolios, founders, and industry trends", "action_count": 36},
    {"id": "dealroom", "name": "Dealroom", "category": "Startup & Business", "description": "Global startup and tech ecosystem data, ecosystem maps, and venture rounds", "action_count": 24},
    {"id": "stripe-atlas", "name": "Stripe Atlas", "category": "Startup & Business", "description": "Delaware C-Corp startup incorporation, EIN generation, and founder stock issuance", "action_count": 18},
    {"id": "pilot", "name": "Pilot Bookkeeping", "category": "Startup & Business", "description": "High-growth startup bookkeeping, financial reporting, and R&D tax credits", "action_count": 22},
    {"id": "bench", "name": "Bench Accounting", "category": "Startup & Business", "description": "Online bookkeeping service and financial statement preparation for founders", "action_count": 20},
    {"id": "taxjar", "name": "TaxJar", "category": "Startup & Business", "description": "Automated sales tax calculation, nexus reporting, and state filing compliance", "action_count": 25},
    {"id": "avalara", "name": "Avalara", "category": "Startup & Business", "description": "Global tax compliance software, VAT calculation, and cross-border customs tax", "action_count": 30},
    {"id": "anaplan", "name": "Anaplan", "category": "Startup & Business", "description": "Connected enterprise financial planning, scenario modeling, and operational budgets", "action_count": 35},
    {"id": "pigment", "name": "Pigment", "category": "Startup & Business", "description": "Business planning platform for real-time headcount, revenue, and budget forecasts", "action_count": 28},
    {"id": "tipalti", "name": "Tipalti", "category": "Startup & Business", "description": "Automated global accounts payable, supplier payments, and tax form collection", "action_count": 30},
    {"id": "airbase", "name": "Airbase", "category": "Startup & Business", "description": "Procure-to-pay spend management, corporate card approvals, and expense accounting", "action_count": 26},
    {"id": "navan", "name": "Navan (TripActions)", "category": "Startup & Business", "description": "Corporate travel booking, corporate cards, and expense management platform", "action_count": 32},

    # ──────────────────────────────────────────────────────────────────────────
    # 3. PRODUCTIVITY & STUDY (70 apps)
    # ──────────────────────────────────────────────────────────────────────────
    {"id": "notion", "name": "Notion", "category": "Productivity & Study", "description": "Search and create workspace docs, databases, and candidate pipelines", "action_count": 64},
    {"id": "obsidian", "name": "Obsidian", "category": "Productivity & Study", "description": "Markdown-based networked personal knowledge graph notes", "action_count": 18},
    {"id": "google-docs", "name": "Google Docs", "category": "Productivity & Study", "description": "Create, format, and collaborate on text documents and resumes", "action_count": 38},
    {"id": "airtable", "name": "Airtable", "category": "Productivity & Study", "description": "Query relational databases, schemas, and candidate pipeline tables", "action_count": 58},
    {"id": "coda", "name": "Coda", "category": "Productivity & Study", "description": "Interactive docs that combine text, tables, and automated buttons", "action_count": 34},
    {"id": "miro", "name": "Miro", "category": "Productivity & Study", "description": "Online visual collaboration whiteboard for architectural diagramming", "action_count": 28},
    {"id": "canvas-lms", "name": "Canvas LMS", "category": "Productivity & Study", "description": "Educational course assignments, gradebook inspect, and student submissions", "action_count": 36},
    {"id": "coursera", "name": "Coursera", "category": "Productivity & Study", "description": "Professional certifications, academic course modules, and skill credentials", "action_count": 28},
    {"id": "google-drive", "name": "Google Drive", "category": "Productivity & Study", "description": "Search, upload, read, and organize workspace cloud files", "action_count": 42},
    {"id": "google-sheets", "name": "Google Sheets", "category": "Productivity & Study", "description": "Read, append, and analyze tabular spreadsheets and reports", "action_count": 52},
    {"id": "google-slides", "name": "Google Slides", "category": "Productivity & Study", "description": "Generate and edit presentation decks and visual packets", "action_count": 28},
    {"id": "google-calendar", "name": "Google Calendar", "category": "Productivity & Study", "description": "Manage schedules, schedule interviews, and query availability", "action_count": 36},
    {"id": "google-forms", "name": "Google Forms", "category": "Productivity & Study", "description": "Inspect form responses and create candidate intake surveys", "action_count": 18},
    {"id": "google-keep", "name": "Google Keep", "category": "Productivity & Study", "description": "Quick notes, task checklists, and personal executive reminders", "action_count": 14},
    {"id": "google-tasks", "name": "Google Tasks", "category": "Productivity & Study", "description": "Create and track task deadlines synced with Google Calendar", "action_count": 16},
    {"id": "asana", "name": "Asana", "category": "Productivity & Study", "description": "Track project milestones, assign tasks, and monitor sprint velocity", "action_count": 46},
    {"id": "clickup", "name": "ClickUp", "category": "Productivity & Study", "description": "All-in-one task management, team goals, and doc workspaces", "action_count": 62},
    {"id": "monday", "name": "Monday.com", "category": "Productivity & Study", "description": "Visual work operating system for tracking enterprise projects", "action_count": 48},
    {"id": "basecamp", "name": "Basecamp", "category": "Productivity & Study", "description": "Team collaboration, message boards, and project check-ins", "action_count": 26},
    {"id": "trello", "name": "Trello", "category": "Productivity & Study", "description": "Kanban boards, lists, and cards for organizing team tasks", "action_count": 32},
    {"id": "confluence", "name": "Confluence", "category": "Productivity & Study", "description": "Enterprise team knowledge base, meeting notes, and project specs", "action_count": 40},
    {"id": "roam-research", "name": "Roam Research", "category": "Productivity & Study", "description": "Bi-directional linked thought notes for research and synthesis", "action_count": 15},
    {"id": "craft", "name": "Craft", "category": "Productivity & Study", "description": "Structured modern document creation and team wiki sharing", "action_count": 22},
    {"id": "evernote", "name": "Evernote", "category": "Productivity & Study", "description": "Capture notes, web clippings, and document archives", "action_count": 25},
    {"id": "box", "name": "Box", "category": "Productivity & Study", "description": "Enterprise cloud content management, encryption, and secure file sharing", "action_count": 36},
    {"id": "dropbox", "name": "Dropbox", "category": "Productivity & Study", "description": "Store, sync, and share candidate documents and portfolio files", "action_count": 38},
    {"id": "onedrive", "name": "Microsoft OneDrive", "category": "Productivity & Study", "description": "Enterprise cloud storage integrated with Microsoft 365", "action_count": 40},
    {"id": "sharepoint", "name": "Microsoft SharePoint", "category": "Productivity & Study", "description": "Company intranets, team document libraries, and access control", "action_count": 44},
    {"id": "microsoft-365", "name": "Microsoft 365", "category": "Productivity & Study", "description": "Access SharePoint, OneDrive, Outlook, and Teams unified suite", "action_count": 68},
    {"id": "canva", "name": "Canva", "category": "Productivity & Study", "description": "Search, create, autofill, and export visual presentations and designs", "action_count": 30},
    {"id": "figma", "name": "Figma", "category": "Productivity & Study", "description": "Inspect design components, extract UI tokens, and query design files", "action_count": 35},
    {"id": "lucidchart", "name": "Lucidchart", "category": "Productivity & Study", "description": "Cloud-based diagramming, process maps, and flowcharts", "action_count": 24},
    {"id": "whimsical", "name": "Whimsical", "category": "Productivity & Study", "description": "Fast flowcharting, wireframing, and team mind maps", "action_count": 20},
    {"id": "todoist", "name": "Todoist", "category": "Productivity & Study", "description": "Organize work and personal tasks with smart natural language scheduling", "action_count": 26},
    {"id": "ticktick", "name": "TickTick", "category": "Productivity & Study", "description": "Task management with Pomodoro timers, habit tracking, and calendars", "action_count": 22},
    {"id": "anydo", "name": "Any.do", "category": "Productivity & Study", "description": "Daily planner, task lists, and calendar integration", "action_count": 18},
    {"id": "onenote", "name": "Microsoft OneNote", "category": "Productivity & Study", "description": "Digital notebook for capturing ideas, meeting notes, and audio", "action_count": 28},
    {"id": "height", "name": "Height", "category": "Productivity & Study", "description": "Autonomous project management tracker with spreadsheet-speed filtering", "action_count": 25},
    {"id": "wrike", "name": "Wrike", "category": "Productivity & Study", "description": "Enterprise work management, Gantt charts, and resource allocation", "action_count": 35},
    {"id": "smartsheet", "name": "Smartsheet", "category": "Productivity & Study", "description": "Spreadsheet-style enterprise project workflows and automation", "action_count": 32},
    {"id": "superhuman", "name": "Superhuman", "category": "Productivity & Study", "description": "The fastest email experience ever made with split inboxes and triage shortcuts", "action_count": 24},
    {"id": "grain", "name": "Grain.com", "category": "Productivity & Study", "description": "AI meeting recorder that transcribes, clips, and summarizes customer calls", "action_count": 26},
    {"id": "fathom", "name": "Fathom", "category": "Productivity & Study", "description": "Free AI meeting recorder that records, transcribes, and summarizes Zoom/Meet calls", "action_count": 24},
    {"id": "otter", "name": "Otter.ai", "category": "Productivity & Study", "description": "AI-powered real-time transcription, meeting notes, and automated team summaries", "action_count": 30},
    {"id": "moodle", "name": "Moodle", "category": "Productivity & Study", "description": "Open-source learning management platform, course quizzes, and student grades", "action_count": 32},
    {"id": "blackboard", "name": "Blackboard Learn", "category": "Productivity & Study", "description": "Higher education LMS, syllabus distribution, exams, and lecture modules", "action_count": 30},
    {"id": "udacity", "name": "Udacity", "category": "Productivity & Study", "description": "Nanodegree technology programs, coding projects, and mentor feedback", "action_count": 24},
    {"id": "edx", "name": "edX", "category": "Productivity & Study", "description": "University-backed online courses, master's degree credits, and certificates", "action_count": 26},
    {"id": "duolingo", "name": "Duolingo", "category": "Productivity & Study", "description": "Language proficiency practice, daily streaks, vocabulary tests, and scores", "action_count": 20},
    {"id": "khan-academy", "name": "Khan Academy", "category": "Productivity & Study", "description": "Math, science, and computing practice exercises and mastery progression", "action_count": 22},
    {"id": "teachable", "name": "Teachable", "category": "Productivity & Study", "description": "Online school creator, video lesson hosting, and student enrollment tracking", "action_count": 28},
    {"id": "thinkific", "name": "Thinkific", "category": "Productivity & Study", "description": "Course authoring platform, student completion tracking, and certifications", "action_count": 26},
    {"id": "skillshare", "name": "Skillshare", "category": "Productivity & Study", "description": "Creative design, illustration, and freelancing video classes and community projects", "action_count": 22},
    {"id": "pluralsight", "name": "Pluralsight", "category": "Productivity & Study", "description": "Enterprise developer skill assessments, learning paths, and cloud labs", "action_count": 25},
    {"id": "codecademy", "name": "Codecademy", "category": "Productivity & Study", "description": "Interactive in-browser programming tutorials, workspaces, and portfolio projects", "action_count": 24},
    {"id": "quizlet", "name": "Quizlet", "category": "Productivity & Study", "description": "Flashcard decks, spaced repetition study sets, and test prep practice", "action_count": 20},
    {"id": "anki", "name": "Anki", "category": "Productivity & Study", "description": "Spaced repetition flashcard software for mastering technical concepts", "action_count": 16},
    {"id": "remnote", "name": "RemNote", "category": "Productivity & Study", "description": "All-in-one tool for networked thinking, note-taking, and automated flashcards", "action_count": 20},
    {"id": "mem-ai", "name": "Mem.ai", "category": "Productivity & Study", "description": "Self-organizing workspace that connects notes and documents using AI", "action_count": 24},
    {"id": "capacities", "name": "Capacities", "category": "Productivity & Study", "description": "Object-based note-taking app for building a personal knowledge studio", "action_count": 22},
    {"id": "walling", "name": "Walling", "category": "Productivity & Study", "description": "Visual idea organization on visual walls for creative and research projects", "action_count": 18},
    {"id": "slite", "name": "Slite", "category": "Productivity & Study", "description": "AI-powered company wiki and documentation tool designed for remote teams", "action_count": 24},
    {"id": "nuclino", "name": "Nuclino", "category": "Productivity & Study", "description": "Collective brain for team wikis, project docs, and visual graph exploration", "action_count": 22},
    {"id": "taskade", "name": "Taskade", "category": "Productivity & Study", "description": "AI-powered workspace for task lists, mind maps, org charts, and video calls", "action_count": 28},
    {"id": "routine", "name": "Routine", "category": "Productivity & Study", "description": "Personal productivity app integrating calendars, agendas, and daily habits", "action_count": 20},
    {"id": "amplenote", "name": "Amplenote", "category": "Productivity & Study", "description": "Idea-to-execution pipeline connecting notes, to-dos, and calendar scheduling", "action_count": 22},
    {"id": "workflowy", "name": "WorkFlowy", "category": "Productivity & Study", "description": "Infinite hierarchical nested bulleted lists for organizing thoughts and research", "action_count": 18},
    {"id": "mindmeister", "name": "MindMeister", "category": "Productivity & Study", "description": "Collaborative online mind mapping tool for brainstorming and structure design", "action_count": 20},
    {"id": "xmind", "name": "XMind", "category": "Productivity & Study", "description": "Full-featured brainstorming and mind mapping software with structured logic charts", "action_count": 18},
    {"id": "pitch-presentation", "name": "Pitch", "category": "Productivity & Study", "description": "Collaborative presentation platform for modern decks, analytics, and templates", "action_count": 26},

    # ──────────────────────────────────────────────────────────────────────────
    # 4. ENGINEERING & CLOUD (97 apps)
    # ──────────────────────────────────────────────────────────────────────────
    {"id": "aws", "name": "Amazon Web Services (AWS)", "category": "Engineering & Cloud", "description": "Cloud infrastructure control across S3, Lambda, EC2, ECS, and CloudWatch", "action_count": 95},
    {"id": "gcp", "name": "Google Cloud Platform (GCP)", "category": "Engineering & Cloud", "description": "Manage BigQuery, Cloud Run, GCS buckets, and IAM governance", "action_count": 88},
    {"id": "azure", "name": "Microsoft Azure", "category": "Engineering & Cloud", "description": "Enterprise cloud services, Azure DevOps, and Blob storage management", "action_count": 78},
    {"id": "vercel", "name": "Vercel", "category": "Engineering & Cloud", "description": "Inspect deployments, preview builds, edge domains, and serverless functions", "action_count": 36},
    {"id": "supabase", "name": "Supabase", "category": "Engineering & Cloud", "description": "Manage PostgreSQL databases, auth policies, vector extensions, and edge storage", "action_count": 52},
    {"id": "neon", "name": "Neon Postgres", "category": "Engineering & Cloud", "description": "Serverless PostgreSQL branching, point-in-time recovery, and compute scaling", "action_count": 28},
    {"id": "postman", "name": "Postman", "category": "Engineering & Cloud", "description": "API collection execution, mock servers, and OpenAPI schema synchronization", "action_count": 35},
    {"id": "sentry", "name": "Sentry", "category": "Engineering & Cloud", "description": "Inspect production exceptions, performance transactions, and error telemetry", "action_count": 38},
    {"id": "datadog", "name": "Datadog", "category": "Engineering & Cloud", "description": "Query server metrics, APM traces, synthetic monitors, and log analytics", "action_count": 55},
    {"id": "bitbucket", "name": "Bitbucket", "category": "Engineering & Cloud", "description": "Atlassian Git code repository management and branch protections", "action_count": 45},
    {"id": "jira", "name": "Jira Software", "category": "Engineering & Cloud", "description": "Track sprint issues, create bug tickets, and sync engineering work", "action_count": 72},
    {"id": "pagerduty", "name": "PagerDuty", "category": "Engineering & Cloud", "description": "Incident management, on-call schedules, and automated escalation policies", "action_count": 34},
    {"id": "grafana", "name": "Grafana", "category": "Engineering & Cloud", "description": "Query telemetry dashboards, Prometheus datasources, and alert rules", "action_count": 40},
    {"id": "prometheus", "name": "Prometheus", "category": "Engineering & Cloud", "description": "Time-series metric monitoring, PromQL querying, and threshold alerting", "action_count": 28},
    {"id": "argocd", "name": "Argo CD", "category": "Engineering & Cloud", "description": "Declarative GitOps continuous delivery for Kubernetes clusters", "action_count": 30},
    {"id": "docker", "name": "Docker Hub", "category": "Engineering & Cloud", "description": "Manage container images, build tags, and repository webhooks", "action_count": 28},
    {"id": "kubernetes", "name": "Kubernetes", "category": "Engineering & Cloud", "description": "Inspect cluster pods, deployments, services, and namespace resources", "action_count": 52},
    {"id": "launchdarkly", "name": "LaunchDarkly", "category": "Engineering & Cloud", "description": "Feature flag toggling, targeting rules, and canary release controls", "action_count": 30},
    {"id": "circleci", "name": "CircleCI", "category": "Engineering & Cloud", "description": "Trigger CI workflows, inspect test artifacts, and view pipeline runs", "action_count": 34},
    {"id": "jenkins", "name": "Jenkins", "category": "Engineering & Cloud", "description": "Manage automated build jobs, pipeline stages, and test execution nodes", "action_count": 36},
    {"id": "hashicorp-vault", "name": "HashiCorp Vault", "category": "Engineering & Cloud", "description": "Enterprise secret management, dynamic credential leases, and PKI certs", "action_count": 35},
    {"id": "terraform", "name": "HashiCorp Terraform", "category": "Engineering & Cloud", "description": "Infrastructure as Code to provision cloud resources across any provider", "action_count": 40},
    {"id": "pulumi", "name": "Pulumi", "category": "Engineering & Cloud", "description": "Modern Infrastructure as Code using real programming languages", "action_count": 34},
    {"id": "cloudflare", "name": "Cloudflare", "category": "Engineering & Cloud", "description": "DNS records, WAF security rules, Workers scripts, and R2 object storage", "action_count": 54},
    {"id": "langfuse", "name": "Langfuse", "category": "Engineering & Cloud", "description": "Open-source LLM engineering platform for traces, evaluations, and prompt management", "action_count": 32},
    {"id": "new-relic", "name": "New Relic", "category": "Engineering & Cloud", "description": "Full-stack observability, NRQL telemetry queries, and distributed tracing", "action_count": 42},
    {"id": "splunk", "name": "Splunk", "category": "Engineering & Cloud", "description": "Security log indexing, enterprise search queries, and SIEM threat monitoring", "action_count": 44},
    {"id": "dynatrace", "name": "Dynatrace", "category": "Engineering & Cloud", "description": "AI-powered application performance monitoring and cloud infrastructure telemetry", "action_count": 38},
    {"id": "honeycomb", "name": "Honeycomb", "category": "Engineering & Cloud", "description": "High-cardinality observability, query analysis, and bubbleup correlation", "action_count": 30},
    {"id": "opsgenie", "name": "Opsgenie", "category": "Engineering & Cloud", "description": "Atlassian on-call alert routing and critical incident dispatching", "action_count": 28},
    {"id": "bugsnag", "name": "Bugsnag", "category": "Engineering & Cloud", "description": "Real-time error monitoring and crash reporting for web and mobile apps", "action_count": 26},
    {"id": "rollbar", "name": "Rollbar", "category": "Engineering & Cloud", "description": "Exception tracking and automated grouping for proactive bug remediation", "action_count": 25},
    {"id": "sonarqube", "name": "SonarQube", "category": "Engineering & Cloud", "description": "Static code analysis, vulnerability detection, and code coverage auditing", "action_count": 30},
    {"id": "prisma", "name": "Prisma Data Platform", "category": "Engineering & Cloud", "description": "ORM schema management, connection pooling, and database migrations", "action_count": 24},
    {"id": "hasura", "name": "Hasura", "category": "Engineering & Cloud", "description": "Instant GraphQL APIs over PostgreSQL, permissions, and remote schemas", "action_count": 32},
    {"id": "flyio", "name": "Fly.io", "category": "Engineering & Cloud", "description": "Deploy Docker containers close to users on bare-metal global servers", "action_count": 28},
    {"id": "railway", "name": "Railway", "category": "Engineering & Cloud", "description": "Instant cloud provisioning for apps, databases, and microservices", "action_count": 26},
    {"id": "render", "name": "Render", "category": "Engineering & Cloud", "description": "Unified cloud platform for static sites, web services, and background workers", "action_count": 28},
    {"id": "koyeb", "name": "Koyeb", "category": "Engineering & Cloud", "description": "Serverless platform for global edge deployment with multi-region scaling", "action_count": 24},
    {"id": "modal", "name": "Modal Labs", "category": "Engineering & Cloud", "description": "High-performance serverless cloud for Python, GPUs, and batch jobs", "action_count": 26},
    {"id": "replicate", "name": "Replicate", "category": "Engineering & Cloud", "description": "Run open-source machine learning models in the cloud with an API", "action_count": 36},
    {"id": "runpod", "name": "RunPod", "category": "Engineering & Cloud", "description": "Distributed GPU cloud computing for AI model inference and fine-tuning", "action_count": 26},
    {"id": "langsmith", "name": "LangSmith", "category": "Engineering & Cloud", "description": "Debug, test, evaluate, and monitor LLM chains and autonomous agents", "action_count": 30},
    {"id": "linearb", "name": "LinearB", "category": "Engineering & Cloud", "description": "Software delivery intelligence platform for tracking engineering cycle times", "action_count": 28},
    {"id": "npm", "name": "NPM Registry", "category": "Engineering & Cloud", "description": "Query package metadata, version releases, and vulnerability advisories", "action_count": 24},
    {"id": "pypi", "name": "PyPI", "category": "Engineering & Cloud", "description": "Python package index releases, wheel downloads, and package dependencies", "action_count": 22},
    {"id": "terraform-cloud", "name": "Terraform Cloud", "category": "Engineering & Cloud", "description": "Remote state execution, module registry, and policy-as-code governance", "action_count": 36},
    {"id": "infisical", "name": "Infisical", "category": "Engineering & Cloud", "description": "End-to-end encrypted secret management and developer config sync", "action_count": 30},
    {"id": "doppler", "name": "Doppler", "category": "Engineering & Cloud", "description": "Universal developer secret ops platform with automated environment sync", "action_count": 28},
    {"id": "1password", "name": "1Password", "category": "Engineering & Cloud", "description": "Enterprise vault credential storage, service accounts, and SSH key management", "action_count": 32},
    {"id": "bitwarden", "name": "Bitwarden", "category": "Engineering & Cloud", "description": "Open-source password manager and secret management CLI", "action_count": 26},
    {"id": "okta", "name": "Okta", "category": "Engineering & Cloud", "description": "Enterprise identity management, SAML SSO, user lifecycle provisioning, and MFA", "action_count": 45},
    {"id": "auth0", "name": "Auth0", "category": "Engineering & Cloud", "description": "Universal identity platform for user authentication, JWT tokens, and social SSO", "action_count": 42},
    {"id": "clerk", "name": "Clerk", "category": "Engineering & Cloud", "description": "Modern user authentication, session tokens, and organization RBAC controls", "action_count": 34},
    {"id": "stytch", "name": "Stytch", "category": "Engineering & Cloud", "description": "Passwordless authentication, passkeys, biometrics, and fraud prevention", "action_count": 28},
    {"id": "kinde", "name": "Kinde", "category": "Engineering & Cloud", "description": "Simple authentication and user management built for modern SaaS applications", "action_count": 26},
    {"id": "firebase", "name": "Google Firebase", "category": "Engineering & Cloud", "description": "Realtime database, Cloud Firestore, authentication, and mobile push triggers", "action_count": 48},
    {"id": "planetscale", "name": "PlanetScale", "category": "Engineering & Cloud", "description": "Serverless MySQL database with Git-like branching and zero-downtime migrations", "action_count": 28},
    {"id": "upstash", "name": "Upstash", "category": "Engineering & Cloud", "description": "Serverless Redis, Kafka, and Vector database with per-request pricing", "action_count": 25},
    {"id": "cockroachdb", "name": "CockroachDB", "category": "Engineering & Cloud", "description": "Distributed SQL database with ACID guarantees and multi-region survivability", "action_count": 32},
    {"id": "clickhouse", "name": "ClickHouse", "category": "Engineering & Cloud", "description": "Ultra-fast column-oriented analytical database for real-time telemetry analytics", "action_count": 42},
    {"id": "snowflake", "name": "Snowflake", "category": "Engineering & Cloud", "description": "Enterprise data cloud, execute analytical SQL queries, and manage data shares", "action_count": 56},
    {"id": "bigquery", "name": "Google BigQuery", "category": "Engineering & Cloud", "description": "Serverless multi-cloud enterprise data warehouse with built-in ML modeling", "action_count": 62},
    {"id": "databricks", "name": "Databricks", "category": "Engineering & Cloud", "description": "Unified lakehouse platform for Apache Spark, delta tables, and ML lifecycle", "action_count": 48},
    {"id": "redshift", "name": "Amazon Redshift", "category": "Engineering & Cloud", "description": "Cloud data warehousing with petabyte-scale analytical query execution", "action_count": 44},
    {"id": "duckdb", "name": "DuckDB", "category": "Engineering & Cloud", "description": "Fast analytical in-process SQL database engine for columnar data processing", "action_count": 22},
    {"id": "motherduck", "name": "MotherDuck", "category": "Engineering & Cloud", "description": "Cloud analytics platform powered by DuckDB for serverless analytical queries", "action_count": 20},
    {"id": "pinecone", "name": "Pinecone", "category": "Engineering & Cloud", "description": "Managed vector database for semantic search, RAG retrieval, and candidate matching", "action_count": 32},
    {"id": "weaviate", "name": "Weaviate", "category": "Engineering & Cloud", "description": "Open-source AI-native vector database with hybrid search and generative modules", "action_count": 34},
    {"id": "qdrant", "name": "Qdrant", "category": "Engineering & Cloud", "description": "Vector similarity search engine with payload filtering for production AI", "action_count": 30},
    {"id": "chroma", "name": "Chroma DB", "category": "Engineering & Cloud", "description": "Embeddings database for building LLM applications with local and cloud storage", "action_count": 24},
    {"id": "milvus", "name": "Milvus", "category": "Engineering & Cloud", "description": "Scalable vector database built for massive billion-scale vector similarity", "action_count": 28},
    {"id": "redis", "name": "Redis", "category": "Engineering & Cloud", "description": "In-memory key-value data store, pub/sub messaging, and distributed caching", "action_count": 36},
    {"id": "postgresql", "name": "PostgreSQL", "category": "Engineering & Cloud", "description": "Advanced open-source relational database with pgvector semantic similarity", "action_count": 48},
    {"id": "mysql", "name": "MySQL", "category": "Engineering & Cloud", "description": "Relational database management, execute SQL queries, and manage tables", "action_count": 40},
    {"id": "mongodb", "name": "MongoDB Atlas", "category": "Engineering & Cloud", "description": "Document-oriented NoSQL database with flexible JSON schemas and vector search", "action_count": 46},
    {"id": "elasticsearch", "name": "Elasticsearch", "category": "Engineering & Cloud", "description": "Distributed full-text search engine, ELK stack analytics, and vector scoring", "action_count": 52},
    {"id": "algolia", "name": "Algolia", "category": "Engineering & Cloud", "description": "Hosted search-as-a-service, instant faceting, and candidate search ranking", "action_count": 34},
    {"id": "meilisearch", "name": "Meilisearch", "category": "Engineering & Cloud", "description": "Lightning-fast, typo-tolerant open-source search engine with custom ranking", "action_count": 28},
    {"id": "typesense", "name": "Typesense", "category": "Engineering & Cloud", "description": "Fast, typo-tolerant open-source search engine designed for instant search UX", "action_count": 26},
    {"id": "neo4j", "name": "Neo4j", "category": "Engineering & Cloud", "description": "Native property graph database, Cypher graph query execution, and knowledge graphs", "action_count": 38},
    {"id": "openai", "name": "OpenAI", "category": "Engineering & Cloud", "description": "Call GPT-4o, generate embeddings, run assistants, and generate DALL-E images", "action_count": 45},
    {"id": "anthropic", "name": "Anthropic Claude", "category": "Engineering & Cloud", "description": "Access Claude 3.5 Sonnet and Haiku models with extended context windows", "action_count": 25},
    {"id": "huggingface", "name": "Hugging Face", "category": "Engineering & Cloud", "description": "Query model inference endpoints, download datasets, and inspect model cards", "action_count": 38},
    {"id": "cohere", "name": "Cohere", "category": "Engineering & Cloud", "description": "Enterprise language models, rerankers, and multi-lingual representation", "action_count": 30},
    {"id": "perplexity", "name": "Perplexity AI", "category": "Engineering & Cloud", "description": "Real-time web research, citations, and factual intelligence synthesis", "action_count": 24},
    {"id": "langchain", "name": "LangChain Hub", "category": "Engineering & Cloud", "description": "Browse and run prompt chains, agents, and custom output parsers", "action_count": 22},
    {"id": "llamaindex", "name": "LlamaIndex", "category": "Engineering & Cloud", "description": "Data framework for connecting custom data sources to large language models", "action_count": 22},
    {"id": "weights-biases", "name": "Weights & Biases", "category": "Engineering & Cloud", "description": "MLOps experiment tracking, dataset versioning, and model registry", "action_count": 32},
    {"id": "mlflow", "name": "MLflow", "category": "Engineering & Cloud", "description": "Open source platform for the complete machine learning lifecycle", "action_count": 28},
    {"id": "tableau", "name": "Tableau", "category": "Engineering & Cloud", "description": "Interactive data visualization, enterprise dashboards, and BI reporting", "action_count": 38},
    {"id": "powerbi", "name": "Microsoft Power BI", "category": "Engineering & Cloud", "description": "Business analytics service providing interactive visualizations and business BI", "action_count": 42},
    {"id": "looker", "name": "Google Looker", "category": "Engineering & Cloud", "description": "Modern enterprise platform for business intelligence and data analytics", "action_count": 36},
    {"id": "metabase", "name": "Metabase", "category": "Engineering & Cloud", "description": "Open source business intelligence tool for fast SQL queries and charts", "action_count": 26},
    {"id": "hex", "name": "Hex Data Platform", "category": "Engineering & Cloud", "description": "Collaborative analytics platform combining SQL, Python, and interactive apps", "action_count": 24},
    {"id": "dbt", "name": "dbt Cloud", "category": "Engineering & Cloud", "description": "Data transformation workflow orchestration, testing, and documentation", "action_count": 34},
    {"id": "airbyte", "name": "Airbyte", "category": "Engineering & Cloud", "description": "ELT data integration platform for synchronizing cloud SaaS data warehouses", "action_count": 30},
    {"id": "fivetran", "name": "Fivetran", "category": "Engineering & Cloud", "description": "Automated data movement platform with zero-maintenance pipelines", "action_count": 32},

    # ──────────────────────────────────────────────────────────────────────────
    # 5. COMMUNICATION & COMMUNITY (58 apps)
    # ──────────────────────────────────────────────────────────────────────────
    {"id": "slack", "name": "Slack", "category": "Communication & Community", "description": "Send notifications, read channels, and manage team communication directly from agent workflows", "action_count": 52},
    {"id": "discord", "name": "Discord", "category": "Communication & Community", "description": "Manage server channels, bot commands, webhooks, and community messages", "action_count": 48},
    {"id": "zoom", "name": "Zoom", "category": "Communication & Community", "description": "Schedule video meetings, manage webinars, and fetch cloud recordings", "action_count": 32},
    {"id": "gmail", "name": "Gmail", "category": "Communication & Community", "description": "Send candidate communications, read thread receipts, and organize mail filters", "action_count": 44},
    {"id": "resend", "name": "Resend", "category": "Communication & Community", "description": "Modern developer email API for sending clean HTML transactional emails", "action_count": 28},
    {"id": "sendgrid", "name": "SendGrid", "category": "Communication & Community", "description": "Send transactional emails, manage email templates, and track delivery rates", "action_count": 40},
    {"id": "microsoft-teams", "name": "Microsoft Teams", "category": "Communication & Community", "description": "Enterprise chat channels, meeting schedules, and organization alerts", "action_count": 46},
    {"id": "telegram", "name": "Telegram", "category": "Communication & Community", "description": "Send bot alerts, query group chats, and broadcast channel updates", "action_count": 38},
    {"id": "whatsapp", "name": "WhatsApp Business", "category": "Communication & Community", "description": "Send template messages, customer notifications, and conversational replies", "action_count": 32},
    {"id": "twitter", "name": "X / Twitter", "category": "Communication & Community", "description": "Post updates, search social mentions, and query developer trends", "action_count": 36},
    {"id": "reddit", "name": "Reddit", "category": "Communication & Community", "description": "Search subreddits, query discussions, and fetch community sentiment", "action_count": 30},
    {"id": "youtube", "name": "YouTube", "category": "Communication & Community", "description": "Query video transcripts, manage channel playlists, and fetch video metrics", "action_count": 35},
    {"id": "google-meet", "name": "Google Meet", "category": "Communication & Community", "description": "Generate video call links and schedule interview video rooms", "action_count": 22},
    {"id": "loom", "name": "Loom", "category": "Communication & Community", "description": "Record screen videos, fetch AI video summaries, and share video links", "action_count": 28},
    {"id": "twilio", "name": "Twilio", "category": "Communication & Community", "description": "Send programmatic SMS text alerts, initiate voice calls, and verify 2FA", "action_count": 42},
    {"id": "mailchimp", "name": "Mailchimp", "category": "Communication & Community", "description": "Manage newsletter subscribers, marketing campaigns, and audience tags", "action_count": 44},
    {"id": "intercom", "name": "Intercom", "category": "Communication & Community", "description": "Live customer messaging, support inbox tickets, and user onboarding tours", "action_count": 48},
    {"id": "zendesk", "name": "Zendesk", "category": "Communication & Community", "description": "Customer support ticketing system, macro triggers, and helpdesk knowledge", "action_count": 56},
    {"id": "front", "name": "Front", "category": "Communication & Community", "description": "Shared team inboxes, email collaboration, and internal ticket assignments", "action_count": 38},
    {"id": "crisp", "name": "Crisp Chat", "category": "Communication & Community", "description": "Live chat widget, knowledge base, and multichannel support inbox", "action_count": 32},
    {"id": "freshdesk", "name": "Freshdesk", "category": "Communication & Community", "description": "Omnichannel customer support ticketing, SLA monitoring, and agent routing", "action_count": 45},
    {"id": "help-scout", "name": "Help Scout", "category": "Communication & Community", "description": "Shared inbox, customer documentation, and customer happiness tracking", "action_count": 36},
    {"id": "customerio", "name": "Customer.io", "category": "Communication & Community", "description": "Automated email and in-app message campaigns driven by real-time customer data", "action_count": 38},
    {"id": "klaviyo", "name": "Klaviyo", "category": "Communication & Community", "description": "E-commerce customer segmentation, automated flows, and SMS marketing", "action_count": 42},
    {"id": "brevo", "name": "Brevo (Sendinblue)", "category": "Communication & Community", "description": "Marketing automation, transactional email, SMS, and WhatsApp campaigns", "action_count": 35},
    {"id": "convertkit", "name": "ConvertKit", "category": "Communication & Community", "description": "Creator email marketing, broadcast emails, and landing page subscribers", "action_count": 30},
    {"id": "postmark", "name": "Postmark", "category": "Communication & Community", "description": "High-deliverability transactional email delivery with bounce tracking", "action_count": 28},
    {"id": "discourse", "name": "Discourse", "category": "Communication & Community", "description": "Community discussion forums, topic posts, and user badge administration", "action_count": 30},
    {"id": "mattermost", "name": "Mattermost", "category": "Communication & Community", "description": "Open-source secure collaboration and chat for technical and security teams", "action_count": 36},
    {"id": "braze", "name": "Braze", "category": "Communication & Community", "description": "Comprehensive customer engagement platform for cross-channel customer journeys", "action_count": 38},
    {"id": "iterable", "name": "Iterable", "category": "Communication & Community", "description": "Cross-channel marketing platform powering unified customer communications", "action_count": 34},
    {"id": "onesignal", "name": "OneSignal", "category": "Communication & Community", "description": "Omnichannel customer engagement with mobile and web push notifications", "action_count": 30},
    {"id": "activecampaign", "name": "ActiveCampaign", "category": "Communication & Community", "description": "Email marketing automation, customer experience, and automated sales outreach", "action_count": 38},
    {"id": "constant-contact", "name": "Constant Contact", "category": "Communication & Community", "description": "Email campaigns, event marketing, and digital audience growth tools", "action_count": 32},
    {"id": "campaign-monitor", "name": "Campaign Monitor", "category": "Communication & Community", "description": "Email marketing templates, transactional emails, and subscriber segmentation", "action_count": 28},
    {"id": "aweber", "name": "AWeber", "category": "Communication & Community", "description": "Email marketing software, landing page builder, and audience autoresponders", "action_count": 26},
    {"id": "moosend", "name": "Moosend", "category": "Communication & Community", "description": "Automated email newsletter delivery, user tracking, and lead forms", "action_count": 24},
    {"id": "mailgun", "name": "Mailgun", "category": "Communication & Community", "description": "Transactional email APIs, validation, and analytics for software developers", "action_count": 32},
    {"id": "amazon-ses", "name": "Amazon SES", "category": "Communication & Community", "description": "High-throughput cloud email sending and receiving service from AWS", "action_count": 34},
    {"id": "messagebird", "name": "MessageBird", "category": "Communication & Community", "description": "Omnichannel communications API for SMS, voice, WhatsApp, and conversations", "action_count": 30},
    {"id": "sinch", "name": "Sinch", "category": "Communication & Community", "description": "Cloud communications platform for programmable messaging, voice, and video", "action_count": 28},
    {"id": "vonage", "name": "Vonage", "category": "Communication & Community", "description": "Communications APIs for voice calls, SMS, video, and two-factor auth", "action_count": 32},
    {"id": "plivo", "name": "Plivo", "category": "Communication & Community", "description": "Cloud communications platform for business SMS and global voice calling", "action_count": 26},
    {"id": "telnyx", "name": "Telnyx", "category": "Communication & Community", "description": "Next-gen communications platform providing SIP trunking, SMS, and wireless IoT", "action_count": 28},
    {"id": "ringcentral", "name": "RingCentral", "category": "Communication & Community", "description": "Cloud phone system, team messaging, video conferencing, and contact centers", "action_count": 36},
    {"id": "dialpad", "name": "Dialpad", "category": "Communication & Community", "description": "AI-powered customer intelligence, business phone system, and call transcription", "action_count": 30},
    {"id": "aircall", "name": "Aircall", "category": "Communication & Community", "description": "Cloud call center and phone system integrated with CRMs and helpdesks", "action_count": 34},
    {"id": "talkdesk", "name": "Talkdesk", "category": "Communication & Community", "description": "Enterprise cloud contact center platform for customer experience and support", "action_count": 32},
    {"id": "livechat", "name": "LiveChat", "category": "Communication & Community", "description": "Customer service platform with live chat, ticket routing, and lead generation", "action_count": 30},
    {"id": "tidio", "name": "Tidio", "category": "Communication & Community", "description": "Live chat and AI chatbot solution for customer engagement and quick support", "action_count": 26},
    {"id": "chatwoot", "name": "Chatwoot", "category": "Communication & Community", "description": "Open-source customer engagement suite and shared inbox for multi-channel support", "action_count": 28},
    {"id": "rocket-chat", "name": "Rocket.Chat", "category": "Communication & Community", "description": "Secure open-source communications platform with team chat and federation", "action_count": 32},
    {"id": "signal", "name": "Signal", "category": "Communication & Community", "description": "End-to-end encrypted private messaging alerts and secure notification channels", "action_count": 20},
    {"id": "wechat", "name": "WeChat Work", "category": "Communication & Community", "description": "Enterprise messaging and office automation tool for international teams", "action_count": 25},
    {"id": "skool", "name": "Skool", "category": "Communication & Community", "description": "Community platform combining course learning, gamification, and discussion boards", "action_count": 24},
    {"id": "circle-so", "name": "Circle.so", "category": "Communication & Community", "description": "All-in-one community platform for creators, students, and member discussions", "action_count": 28},
    {"id": "mighty-networks", "name": "Mighty Networks", "category": "Communication & Community", "description": "Community, online courses, sales, and livestream events in one place", "action_count": 26},
    {"id": "geneva", "name": "Geneva", "category": "Communication & Community", "description": "Group chat platform for communities with rooms, audio stages, and events", "action_count": 22},
]
