"""Enterprise Composio App Catalog (260+ Integrations).

Provides comprehensive metadata for all official Composio SaaS integrations,
enabling zero-trust catalog discovery, category filtering, search, and dynamic
OAuth connection initiation.
"""

from typing import Any, Dict, List

COMPOSIO_SUPPORTED_APPS: List[Dict[str, Any]] = [
    # ──────────────────────────────────────────────────────────────────────────
    # 1. PRODUCTIVITY & COLLABORATION (40 apps)
    # ──────────────────────────────────────────────────────────────────────────
    {"id": "notion", "name": "Notion", "category": "Productivity", "description": "Search and create workspace docs, databases, and candidate pipelines", "action_count": 64},
    {"id": "google-drive", "name": "Google Drive", "category": "Productivity", "description": "Search, upload, read, and organize workspace cloud files", "action_count": 42},
    {"id": "google-docs", "name": "Google Docs", "category": "Productivity", "description": "Create, format, and collaborate on text documents and resumes", "action_count": 38},
    {"id": "google-sheets", "name": "Google Sheets", "category": "Productivity", "description": "Read, append, and analyze tabular spreadsheets and reports", "action_count": 52},
    {"id": "google-slides", "name": "Google Slides", "category": "Productivity", "description": "Generate and edit presentation decks and visual packets", "action_count": 28},
    {"id": "google-calendar", "name": "Google Calendar", "category": "Productivity", "description": "Manage schedules, schedule interviews, and query availability", "action_count": 36},
    {"id": "google-forms", "name": "Google Forms", "category": "Productivity", "description": "Inspect form responses and create candidate intake surveys", "action_count": 18},
    {"id": "google-keep", "name": "Google Keep", "category": "Productivity", "description": "Quick notes, task checklists, and personal executive reminders", "action_count": 14},
    {"id": "google-tasks", "name": "Google Tasks", "category": "Productivity", "description": "Create and track task deadlines synced with Google Calendar", "action_count": 16},
    {"id": "airtable", "name": "Airtable", "category": "Productivity", "description": "Query relational databases, schemas, and candidate pipeline tables", "action_count": 58},
    {"id": "asana", "name": "Asana", "category": "Productivity", "description": "Track project milestones, assign tasks, and monitor sprint velocity", "action_count": 46},
    {"id": "coda", "name": "Coda", "category": "Productivity", "description": "Interactive docs that combine text, tables, and automated buttons", "action_count": 34},
    {"id": "clickup", "name": "ClickUp", "category": "Productivity", "description": "All-in-one task management, team goals, and doc workspaces", "action_count": 62},
    {"id": "monday", "name": "Monday.com", "category": "Productivity", "description": "Visual work operating system for tracking enterprise projects", "action_count": 48},
    {"id": "basecamp", "name": "Basecamp", "category": "Productivity", "description": "Team collaboration, message boards, and project check-ins", "action_count": 26},
    {"id": "trello", "name": "Trello", "category": "Productivity", "description": "Kanban boards, lists, and cards for organizing team tasks", "action_count": 32},
    {"id": "confluence", "name": "Confluence", "category": "Productivity", "description": "Enterprise team knowledge base, meeting notes, and project specs", "action_count": 40},
    {"id": "obsidian", "name": "Obsidian", "category": "Productivity", "description": "Markdown-based networked personal knowledge graph notes", "action_count": 18},
    {"id": "roam-research", "name": "Roam Research", "category": "Productivity", "description": "Bi-directional linked thought notes for research and synthesis", "action_count": 15},
    {"id": "craft", "name": "Craft", "category": "Productivity", "description": "Structured modern document creation and team wiki sharing", "action_count": 22},
    {"id": "evernote", "name": "Evernote", "category": "Productivity", "description": "Capture notes, web clippings, and document archives", "action_count": 25},
    {"id": "box", "name": "Box", "category": "Productivity", "description": "Enterprise cloud content management, encryption, and secure file sharing", "action_count": 36},
    {"id": "dropbox", "name": "Dropbox", "category": "Productivity", "description": "Store, sync, and share candidate documents and portfolio files", "action_count": 38},
    {"id": "onedrive", "name": "Microsoft OneDrive", "category": "Productivity", "description": "Enterprise cloud storage integrated with Microsoft 365", "action_count": 40},
    {"id": "sharepoint", "name": "Microsoft SharePoint", "category": "Productivity", "description": "Company intranets, team document libraries, and access control", "action_count": 44},
    {"id": "microsoft-365", "name": "Microsoft 365", "category": "Productivity", "description": "Access SharePoint, OneDrive, Outlook, and Teams unified suite", "action_count": 68},
    {"id": "canva", "name": "Canva", "category": "Productivity", "description": "Search, create, autofill, and export visual presentations and designs", "action_count": 30},
    {"id": "figma", "name": "Figma", "category": "Productivity", "description": "Inspect design components, extract UI tokens, and query design files", "action_count": 35},
    {"id": "miro", "name": "Miro", "category": "Productivity", "description": "Online visual collaboration whiteboard for architectural diagramming", "action_count": 28},
    {"id": "lucidchart", "name": "Lucidchart", "category": "Productivity", "description": "Cloud-based diagramming, process maps, and flowcharts", "action_count": 24},
    {"id": "whimsical", "name": "Whimsical", "category": "Productivity", "description": "Fast flowcharting, wireframing, and team mind maps", "action_count": 20},
    {"id": "todoist", "name": "Todoist", "category": "Productivity", "description": "Organize work and personal tasks with smart natural language scheduling", "action_count": 26},
    {"id": "ticktick", "name": "TickTick", "category": "Productivity", "description": "Task management with Pomodoro timers, habit tracking, and calendars", "action_count": 22},
    {"id": "anydo", "name": "Any.do", "category": "Productivity", "description": "Daily planner, task lists, and calendar integration", "action_count": 18},
    {"id": "onenote", "name": "Microsoft OneNote", "category": "Productivity", "description": "Digital notebook for capturing ideas, meeting notes, and audio", "action_count": 28},
    {"id": "height", "name": "Height", "category": "Productivity", "description": "Autonomous project management tracker with spreadsheet-speed filtering", "action_count": 25},
    {"id": "wrike", "name": "Wrike", "category": "Productivity", "description": "Enterprise work management, Gantt charts, and resource allocation", "action_count": 35},
    {"id": "smartsheet", "name": "Smartsheet", "category": "Productivity", "description": "Spreadsheet-style enterprise project workflows and automation", "action_count": 32},
    {"id": "linear", "name": "Linear", "category": "Productivity", "description": "Issue tracking, cycle management, and roadmap synchronization", "action_count": 54},

    # ──────────────────────────────────────────────────────────────────────────
    # 2. ENGINEERING & DEVOPS (50 apps)
    # ──────────────────────────────────────────────────────────────────────────
    {"id": "github", "name": "GitHub", "category": "Engineering", "description": "Inspect PRs, manage issues, read repositories, and trigger automated branch workflows", "action_count": 82},
    {"id": "gitlab", "name": "GitLab", "category": "Engineering", "description": "Manage repositories, CI/CD pipelines, and merge request approvals", "action_count": 68},
    {"id": "bitbucket", "name": "Bitbucket", "category": "Engineering", "description": "Atlassian Git code repository management and branch protections", "action_count": 45},
    {"id": "jira", "name": "Jira Software", "category": "Engineering", "description": "Track sprint issues, create bug tickets, and sync engineering work", "action_count": 72},
    {"id": "sentry", "name": "Sentry", "category": "Engineering", "description": "Inspect production exceptions, performance transactions, and error telemetry", "action_count": 38},
    {"id": "datadog", "name": "Datadog", "category": "Engineering", "description": "Query server metrics, APM traces, synthetic monitors, and log analytics", "action_count": 55},
    {"id": "pagerduty", "name": "PagerDuty", "category": "Engineering", "description": "Incident management, on-call schedules, and automated escalation policies", "action_count": 34},
    {"id": "grafana", "name": "Grafana", "category": "Engineering", "description": "Query telemetry dashboards, Prometheus datasources, and alert rules", "action_count": 40},
    {"id": "docker", "name": "Docker Hub", "category": "Engineering", "description": "Manage container images, build tags, and repository webhooks", "action_count": 26},
    {"id": "kubernetes", "name": "Kubernetes", "category": "Engineering", "description": "Inspect cluster pods, deployments, services, and namespace resources", "action_count": 48},
    {"id": "aws", "name": "Amazon Web Services (AWS)", "category": "Engineering", "description": "Cloud infrastructure control across S3, Lambda, EC2, ECS, and CloudWatch", "action_count": 95},
    {"id": "gcp", "name": "Google Cloud Platform (GCP)", "category": "Engineering", "description": "Manage BigQuery, Cloud Run, GCS buckets, and IAM governance", "action_count": 88},
    {"id": "azure", "name": "Microsoft Azure", "category": "Engineering", "description": "Enterprise cloud services, Azure DevOps, and Blob storage management", "action_count": 78},
    {"id": "vercel", "name": "Vercel", "category": "Engineering", "description": "Inspect deployments, preview builds, edge domains, and serverless functions", "action_count": 36},
    {"id": "supabase", "name": "Supabase", "category": "Engineering", "description": "Manage PostgreSQL databases, auth policies, vector extensions, and edge storage", "action_count": 52},
    {"id": "neon", "name": "Neon Postgres", "category": "Engineering", "description": "Serverless PostgreSQL branching, point-in-time recovery, and compute scaling", "action_count": 28},
    {"id": "postman", "name": "Postman", "category": "Engineering", "description": "API collection execution, mock servers, and OpenAPI schema synchronization", "action_count": 32},
    {"id": "launchdarkly", "name": "LaunchDarkly", "category": "Engineering", "description": "Feature flag toggling, targeting rules, and canary release controls", "action_count": 30},
    {"id": "circleci", "name": "CircleCI", "category": "Engineering", "description": "Trigger CI workflows, inspect test artifacts, and view pipeline runs", "action_count": 34},
    {"id": "jenkins", "name": "Jenkins", "category": "Engineering", "description": "Manage automated build jobs, pipeline stages, and test execution nodes", "action_count": 36},
    {"id": "hashicorp-vault", "name": "HashiCorp Vault", "category": "Engineering", "description": "Enterprise secret management, dynamic credential leases, and PKI certs", "action_count": 35},
    {"id": "npm", "name": "NPM Registry", "category": "Engineering", "description": "Query package metadata, version releases, and vulnerability advisories", "action_count": 24},
    {"id": "cloudflare", "name": "Cloudflare", "category": "Engineering", "description": "DNS records, WAF security rules, Workers scripts, and R2 object storage", "action_count": 54},
    {"id": "langfuse", "name": "Langfuse", "category": "Engineering", "description": "Open-source LLM engineering platform for traces, evaluations, and prompt management", "action_count": 32},
    {"id": "pulumi", "name": "Pulumi", "category": "Engineering", "description": "Infrastructure as code in general-purpose languages with state management", "action_count": 28},
    {"id": "terraform-cloud", "name": "Terraform Cloud", "category": "Engineering", "description": "Remote state execution, module registry, and policy-as-code governance", "action_count": 36},
    {"id": "new-relic", "name": "New Relic", "category": "Engineering", "description": "Full-stack observability, NRQL telemetry queries, and distributed tracing", "action_count": 42},
    {"id": "splunk", "name": "Splunk", "category": "Engineering", "description": "Security log indexing, enterprise search queries, and SIEM threat monitoring", "action_count": 44},
    {"id": "dynatrace", "name": "Dynatrace", "category": "Engineering", "description": "AI-powered application performance monitoring and cloud infrastructure telemetry", "action_count": 38},
    {"id": "honeycomb", "name": "Honeycomb", "category": "Engineering", "description": "High-cardinality observability, query analysis, and bubbleup correlation", "action_count": 30},
    {"id": "opsgenie", "name": "Opsgenie", "category": "Engineering", "description": "Atlassian on-call alert routing and critical incident dispatching", "action_count": 28},
    {"id": "bugsnag", "name": "Bugsnag", "category": "Engineering", "description": "Real-time error monitoring and crash reporting for web and mobile apps", "action_count": 26},
    {"id": "rollbar", "name": "Rollbar", "category": "Engineering", "description": "Exception tracking and automated grouping for proactive bug remediation", "action_count": 25},
    {"id": "sonarqube", "name": "SonarQube", "category": "Engineering", "description": "Static code analysis, vulnerability detection, and code coverage auditing", "action_count": 30},
    {"id": "prisma", "name": "Prisma Data Platform", "category": "Engineering", "description": "ORM schema management, connection pooling, and database migrations", "action_count": 24},
    {"id": "hasura", "name": "Hasura", "category": "Engineering", "description": "Instant GraphQL APIs over PostgreSQL, permissions, and remote schemas", "action_count": 32},
    {"id": "flyio", "name": "Fly.io", "category": "Engineering", "description": "Deploy Docker containers close to users on bare-metal global servers", "action_count": 28},
    {"id": "railway", "name": "Railway", "category": "Engineering", "description": "Instant cloud provisioning for apps, databases, and microservices", "action_count": 26},
    {"id": "render", "name": "Render", "category": "Engineering", "description": "Unified cloud platform for static sites, web services, and background workers", "action_count": 28},
    {"id": "koyeb", "name": "Koyeb", "category": "Engineering", "description": "Serverless platform for global edge deployment with multi-region scaling", "action_count": 24},
    {"id": "modal", "name": "Modal Labs", "category": "Engineering", "description": "High-performance serverless cloud for Python, GPUs, and batch jobs", "action_count": 26},
    {"id": "replicate", "name": "Replicate", "category": "Engineering", "description": "Run open-source machine learning models in the cloud with an API", "action_count": 34},
    {"id": "runpod", "name": "RunPod", "category": "Engineering", "description": "Distributed GPU cloud computing for AI model inference and fine-tuning", "action_count": 26},
    {"id": "langsmith", "name": "LangSmith", "category": "Engineering", "description": "Debug, test, evaluate, and monitor LLM chains and autonomous agents", "action_count": 30},
    {"id": "prometheus", "name": "Prometheus", "category": "Engineering", "description": "Time-series metric monitoring, PromQL querying, and threshold alerting", "action_count": 28},
    {"id": "argocd", "name": "Argo CD", "category": "Engineering", "description": "Declarative GitOps continuous delivery for Kubernetes clusters", "action_count": 30},

    # ──────────────────────────────────────────────────────────────────────────
    # 3. COMMUNICATION & MESSAGING (35 apps)
    # ──────────────────────────────────────────────────────────────────────────
    {"id": "slack", "name": "Slack", "category": "Communication", "description": "Send notifications, read channels, and manage team communication directly from agent workflows", "action_count": 52},
    {"id": "discord", "name": "Discord", "category": "Communication", "description": "Manage server channels, bot commands, webhooks, and community messages", "action_count": 48},
    {"id": "microsoft-teams", "name": "Microsoft Teams", "category": "Communication", "description": "Enterprise chat channels, meeting schedules, and organization alerts", "action_count": 46},
    {"id": "telegram", "name": "Telegram", "category": "Communication", "description": "Send bot alerts, query group chats, and broadcast channel updates", "action_count": 38},
    {"id": "whatsapp", "name": "WhatsApp Business", "category": "Communication", "description": "Send template messages, customer notifications, and conversational replies", "action_count": 32},
    {"id": "twitter", "name": "X / Twitter", "category": "Communication", "description": "Post updates, search social mentions, and query developer trends", "action_count": 36},
    {"id": "linkedin", "name": "LinkedIn", "category": "Communication", "description": "Post professional updates, fetch company profiles, and discover job listings", "action_count": 34},
    {"id": "reddit", "name": "Reddit", "category": "Communication", "description": "Search subreddits, query discussions, and fetch community sentiment", "action_count": 30},
    {"id": "youtube", "name": "YouTube", "category": "Communication", "description": "Query video transcripts, manage channel playlists, and fetch video metrics", "action_count": 35},
    {"id": "zoom", "name": "Zoom", "category": "Communication", "description": "Schedule video meetings, manage webinars, and fetch cloud recordings", "action_count": 32},
    {"id": "google-meet", "name": "Google Meet", "category": "Communication", "description": "Generate video call links and schedule interview video rooms", "action_count": 22},
    {"id": "loom", "name": "Loom", "category": "Communication", "description": "Record screen videos, fetch AI video summaries, and share video links", "action_count": 25},
    {"id": "twilio", "name": "Twilio", "category": "Communication", "description": "Send programmatic SMS text alerts, initiate voice calls, and verify 2FA", "action_count": 42},
    {"id": "sendgrid", "name": "SendGrid", "category": "Communication", "description": "Send transactional emails, manage email templates, and track delivery rates", "action_count": 38},
    {"id": "mailchimp", "name": "Mailchimp", "category": "Communication", "description": "Manage newsletter subscribers, marketing campaigns, and audience tags", "action_count": 44},
    {"id": "resend", "name": "Resend", "category": "Communication", "description": "Modern developer email API for sending clean HTML transactional emails", "action_count": 28},
    {"id": "intercom", "name": "Intercom", "category": "Communication", "description": "Live customer messaging, support inbox tickets, and user onboarding tours", "action_count": 48},
    {"id": "zendesk", "name": "Zendesk", "category": "Communication", "description": "Customer support ticketing system, macro triggers, and helpdesk knowledge", "action_count": 56},
    {"id": "front", "name": "Front", "category": "Communication", "description": "Shared team inboxes, email collaboration, and internal ticket assignments", "action_count": 38},
    {"id": "crisp", "name": "Crisp Chat", "category": "Communication", "description": "Live chat widget, knowledge base, and multichannel support inbox", "action_count": 32},
    {"id": "freshdesk", "name": "Freshdesk", "category": "Communication", "description": "Omnichannel customer support ticketing, SLA monitoring, and agent routing", "action_count": 45},
    {"id": "help-scout", "name": "Help Scout", "category": "Communication", "description": "Shared inbox, customer documentation, and customer happiness tracking", "action_count": 36},
    {"id": "customerio", "name": "Customer.io", "category": "Communication", "description": "Automated email and in-app message campaigns driven by real-time customer data", "action_count": 38},
    {"id": "klaviyo", "name": "Klaviyo", "category": "Communication", "description": "E-commerce customer segmentation, automated flows, and SMS marketing", "action_count": 42},
    {"id": "brevo", "name": "Brevo (Sendinblue)", "category": "Communication", "description": "Marketing automation, transactional email, SMS, and WhatsApp campaigns", "action_count": 35},
    {"id": "convertkit", "name": "ConvertKit", "category": "Communication", "description": "Creator email marketing, broadcast emails, and landing page subscribers", "action_count": 30},
    {"id": "postmark", "name": "Postmark", "category": "Communication", "description": "High-deliverability transactional email delivery with bounce tracking", "action_count": 26},
    {"id": "discourse", "name": "Discourse", "category": "Communication", "description": "Community discussion forums, topic posts, and user badge administration", "action_count": 30},
    {"id": "mattermost", "name": "Mattermost", "category": "Communication", "description": "Open-source secure collaboration and chat for technical and security teams", "action_count": 34},

    # ──────────────────────────────────────────────────────────────────────────
    # 4. SALES, CRM & REVENUE (35 apps)
    # ──────────────────────────────────────────────────────────────────────────
    {"id": "hubspot", "name": "HubSpot", "category": "Sales", "description": "CRM contacts, deal stages, company profiles, and marketing lead automation", "action_count": 76},
    {"id": "salesforce", "name": "Salesforce", "category": "Sales", "description": "Enterprise customer 360, lead pipelines, opportunities, and SOQL queries", "action_count": 84},
    {"id": "pipedrive", "name": "Pipedrive", "category": "Sales", "description": "Visual pipeline sales CRM for managing activity and closing deals", "action_count": 52},
    {"id": "zoho-crm", "name": "Zoho CRM", "category": "Sales", "description": "Lead scoring, deal progression, and sales automation for global teams", "action_count": 58},
    {"id": "close", "name": "Close CRM", "category": "Sales", "description": "Inside sales CRM with built-in calling, SMS, and email sequencing", "action_count": 46},
    {"id": "attio", "name": "Attio", "category": "Sales", "description": "Next-generation relational CRM built with real-time data sync and custom objects", "action_count": 40},
    {"id": "apollo", "name": "Apollo.io", "category": "Sales", "description": "B2B lead intelligence, executive contact enrichment, and sales sequencing", "action_count": 45},
    {"id": "gong", "name": "Gong.io", "category": "Sales", "description": "Revenue intelligence platform analyzing sales calls, deals, and customer sentiment", "action_count": 32},
    {"id": "outreach", "name": "Outreach", "category": "Sales", "description": "Sales engagement platform, automated prospect sequences, and pipeline tracking", "action_count": 48},
    {"id": "clay", "name": "Clay", "category": "Sales", "description": "Programmatic outbound prospecting, waterfall data enrichment, and AI scoring", "action_count": 36},
    {"id": "salesloft", "name": "Salesloft", "category": "Sales", "description": "Sales execution platform for managing customer cadences and opportunity forecasting", "action_count": 42},
    {"id": "lemlist", "name": "Lemlist", "category": "Sales", "description": "Personalized cold email outreach with dynamic image and video personalization", "action_count": 30},
    {"id": "instantly", "name": "Instantly.ai", "category": "Sales", "description": "Unlimited email warm-up, deliverability network, and bulk cold outreach", "action_count": 28},
    {"id": "woodpecker", "name": "Woodpecker", "category": "Sales", "description": "Automated cold email outreach with human-like sending rhythms", "action_count": 26},
    {"id": "phantombuster", "name": "PhantomBuster", "category": "Sales", "description": "Automated lead generation, LinkedIn profile scrapers, and web data extraction", "action_count": 32},
    {"id": "lusha", "name": "Lusha", "category": "Sales", "description": "Direct phone numbers, corporate email addresses, and company firmographics", "action_count": 25},
    {"id": "hunter", "name": "Hunter.io", "category": "Sales", "description": "Find and verify professional email addresses by company domain name", "action_count": 28},
    {"id": "clearbit", "name": "Clearbit", "category": "Sales", "description": "Real-time B2B company enrichment, website IP deanonymization, and lead scoring", "action_count": 34},
    {"id": "zoominfo", "name": "ZoomInfo", "category": "Sales", "description": "Comprehensive B2B company intelligence, org charts, and executive contact data", "action_count": 40},
    {"id": "cognism", "name": "Cognism", "category": "Sales", "description": "GDPR-compliant global B2B phone and email contact data", "action_count": 30},
    {"id": "freshsales", "name": "Freshsales", "category": "Sales", "description": "AI-powered sales CRM with built-in phone, email, and activity tracking", "action_count": 38},
    {"id": "copper", "name": "Copper CRM", "category": "Sales", "description": "Google Workspace-native CRM for managing customer relationships in Gmail", "action_count": 34},
    {"id": "insightly", "name": "Insightly", "category": "Sales", "description": "Combined CRM and project management for growing businesses", "action_count": 36},
    {"id": "demandbase", "name": "Demandbase", "category": "Sales", "description": "Account-based marketing (ABM), intent data, and B2B ad targeting", "action_count": 28},
    {"id": "6sense", "name": "6sense", "category": "Sales", "description": "Predictive account intent and buyer journey intelligence platform", "action_count": 26},

    # ──────────────────────────────────────────────────────────────────────────
    # 5. FINANCE, BILLING & COMMERCE (25 apps)
    # ──────────────────────────────────────────────────────────────────────────
    {"id": "stripe", "name": "Stripe", "category": "Finance", "description": "Process payments, manage customer subscriptions, query invoices, and balance ledgers", "action_count": 68},
    {"id": "paypal", "name": "PayPal", "category": "Finance", "description": "Online payment gateway, merchant invoicing, and transaction status queries", "action_count": 38},
    {"id": "square", "name": "Square", "category": "Finance", "description": "Point-of-sale payments, merchant orders, customer records, and inventory", "action_count": 42},
    {"id": "quickbooks", "name": "QuickBooks Online", "category": "Finance", "description": "Enterprise bookkeeping, chart of accounts, expense reports, and tax ledgers", "action_count": 54},
    {"id": "xero", "name": "Xero", "category": "Finance", "description": "Small business cloud accounting, bank feeds, reconciliation, and invoicing", "action_count": 48},
    {"id": "shopify", "name": "Shopify", "category": "Finance", "description": "E-commerce catalog management, customer orders, shipping labels, and inventory", "action_count": 65},
    {"id": "chargebee", "name": "Chargebee", "category": "Finance", "description": "Subscription billing automation, revenue recognition, and churn analytics", "action_count": 44},
    {"id": "recurly", "name": "Recurly", "category": "Finance", "description": "Recurring billing engine, payment optimization, and subscription lifecycle management", "action_count": 36},
    {"id": "brex", "name": "Brex", "category": "Finance", "description": "Corporate credit cards, spend management, expense approvals, and budget tracking", "action_count": 32},
    {"id": "ramp", "name": "Ramp", "category": "Finance", "description": "Corporate card spend controls, automated receipt matching, and vendor savings", "action_count": 34},
    {"id": "mercury", "name": "Mercury Bank", "category": "Finance", "description": "Tech banking platform, wire transfers, transaction search, and account balances", "action_count": 28},
    {"id": "gusto", "name": "Gusto", "category": "Finance", "description": "Automated payroll processing, employee benefits, and contractor payments", "action_count": 42},
    {"id": "wave", "name": "Wave Accounting", "category": "Finance", "description": "Free invoicing, receipt scanning, and simple accounting for freelancers", "action_count": 24},
    {"id": "freshbooks", "name": "FreshBooks", "category": "Finance", "description": "Cloud accounting software for client invoicing, time tracking, and expenses", "action_count": 36},
    {"id": "bill", "name": "Bill.com", "category": "Finance", "description": "Accounts payable and receivable automation with multi-level approval workflows", "action_count": 38},
    {"id": "expensify", "name": "Expensify", "category": "Finance", "description": "Automated expense report receipt scanning and corporate reimbursement", "action_count": 30},
    {"id": "deel", "name": "Deel", "category": "Finance", "description": "Global contractor hiring, compliance contracts, payroll, and tax forms", "action_count": 46},
    {"id": "wise", "name": "Wise (TransferWise)", "category": "Finance", "description": "International multi-currency bank transfers, currency exchange, and balance queries", "action_count": 32},
    {"id": "paddle", "name": "Paddle", "category": "Finance", "description": "Merchant of record for SaaS software sales, global tax compliance, and billing", "action_count": 36},
    {"id": "lemon-squeezy", "name": "Lemon Squeezy", "category": "Finance", "description": "Payments, tax, and subscriptions for digital products and SaaS software", "action_count": 30},
    {"id": "plaid", "name": "Plaid", "category": "Finance", "description": "Connect user bank accounts, verify account balances, and fetch transaction history", "action_count": 35},
    {"id": "netsuite", "name": "Oracle NetSuite", "category": "Finance", "description": "Enterprise cloud ERP system, financial consolidation, and inventory control", "action_count": 60},

    # ──────────────────────────────────────────────────────────────────────────
    # 6. AI & DATA PLATFORMS (40 apps)
    # ──────────────────────────────────────────────────────────────────────────
    {"id": "openai", "name": "OpenAI", "category": "AI & Data", "description": "Call GPT-4o, generate embeddings, run assistants, and generate DALL-E images", "action_count": 45},
    {"id": "anthropic", "name": "Anthropic Claude", "category": "AI & Data", "description": "Access Claude 3.5 Sonnet and Haiku models with extended context windows", "action_count": 25},
    {"id": "huggingface", "name": "Hugging Face", "category": "AI & Data", "description": "Query model inference endpoints, download datasets, and inspect model cards", "action_count": 38},
    {"id": "pinecone", "name": "Pinecone", "category": "AI & Data", "description": "Managed vector database for semantic search, RAG retrieval, and candidate matching", "action_count": 32},
    {"id": "weaviate", "name": "Weaviate", "category": "AI & Data", "description": "Open-source AI-native vector database with hybrid search and generative modules", "action_count": 34},
    {"id": "qdrant", "name": "Qdrant", "category": "AI & Data", "description": "Vector similarity search engine with payload filtering for production AI", "action_count": 30},
    {"id": "chroma", "name": "Chroma DB", "category": "AI & Data", "description": "Embeddings database for building LLM applications with local and cloud storage", "action_count": 24},
    {"id": "milvus", "name": "Milvus", "category": "AI & Data", "description": "Scalable vector database built for massive billion-scale vector similarity", "action_count": 28},
    {"id": "snowflake", "name": "Snowflake", "category": "AI & Data", "description": "Enterprise data cloud, execute analytical SQL queries, and manage data shares", "action_count": 56},
    {"id": "bigquery", "name": "Google BigQuery", "category": "AI & Data", "description": "Serverless multi-cloud enterprise data warehouse with built-in ML modeling", "action_count": 62},
    {"id": "clickhouse", "name": "ClickHouse", "category": "AI & Data", "description": "Ultra-fast column-oriented analytical database for real-time telemetry analytics", "action_count": 42},
    {"id": "redis", "name": "Redis", "category": "AI & Data", "description": "In-memory key-value data store, pub/sub messaging, and distributed caching", "action_count": 36},
    {"id": "postgresql", "name": "PostgreSQL", "category": "AI & Data", "description": "Advanced open-source relational database with pgvector semantic similarity", "action_count": 48},
    {"id": "mysql", "name": "MySQL", "category": "AI & Data", "description": "Relational database management, execute SQL queries, and manage tables", "action_count": 40},
    {"id": "mongodb", "name": "MongoDB Atlas", "category": "AI & Data", "description": "Document-oriented NoSQL database with flexible JSON schemas and vector search", "action_count": 46},
    {"id": "elasticsearch", "name": "Elasticsearch", "category": "AI & Data", "description": "Distributed full-text search engine, ELK stack analytics, and vector scoring", "action_count": 52},
    {"id": "algolia", "name": "Algolia", "category": "AI & Data", "description": "Hosted search-as-a-service, instant faceting, and candidate search ranking", "action_count": 34},
    {"id": "meilisearch", "name": "Meilisearch", "category": "AI & Data", "description": "Lightning-fast, typo-tolerant open-source search engine with custom ranking", "action_count": 28},
    {"id": "typesense", "name": "Typesense", "category": "AI & Data", "description": "Fast, typo-tolerant open-source search engine designed for instant search UX", "action_count": 26},
    {"id": "databricks", "name": "Databricks", "category": "AI & Data", "description": "Unified lakehouse platform for Apache Spark, delta tables, and ML lifecycle", "action_count": 48},
    {"id": "redshift", "name": "Amazon Redshift", "category": "AI & Data", "description": "Cloud data warehousing with petabyte-scale analytical query execution", "action_count": 44},
    {"id": "duckdb", "name": "DuckDB", "category": "AI & Data", "description": "Fast analytical in-process SQL database engine for columnar data processing", "action_count": 22},
    {"id": "neo4j", "name": "Neo4j", "category": "AI & Data", "description": "Native property graph database, Cypher graph query execution, and knowledge graphs", "action_count": 38},
    {"id": "planetscale", "name": "PlanetScale", "category": "AI & Data", "description": "Serverless MySQL database with Git-like branching and zero-downtime migrations", "action_count": 28},
    {"id": "upstash", "name": "Upstash", "category": "AI & Data", "description": "Serverless Redis, Kafka, and Vector database with per-request pricing", "action_count": 25},

    # ──────────────────────────────────────────────────────────────────────────
    # 7. HR, TALENT & RECRUITING (35 apps)
    # ──────────────────────────────────────────────────────────────────────────
    {"id": "greenhouse", "name": "Greenhouse ATS", "category": "HR & Recruiting", "description": "Candidate pipeline stages, scorecards, job postings, and interview schedules", "action_count": 54},
    {"id": "lever", "name": "Lever ATS", "category": "HR & Recruiting", "description": "Applicant tracking, candidate sourcing, requisition approvals, and interviews", "action_count": 48},
    {"id": "ashby", "name": "Ashby ATS", "category": "HR & Recruiting", "description": "Modern all-in-one recruiting platform with structured candidate interviews and analytics", "action_count": 44},
    {"id": "workday", "name": "Workday", "category": "HR & Recruiting", "description": "Enterprise human capital management, organizational hierarchies, and payroll", "action_count": 58},
    {"id": "bamboohr", "name": "BambooHR", "category": "HR & Recruiting", "description": "Employee directory, time-off requests, onboarding packets, and performance reviews", "action_count": 42},
    {"id": "rippling", "name": "Rippling", "category": "HR & Recruiting", "description": "Unified workforce platform managing HR, employee IT devices, and payroll", "action_count": 48},
    {"id": "remote", "name": "Remote.com", "category": "HR & Recruiting", "description": "Global employer of record, international compliance, payroll, and benefits", "action_count": 36},
    {"id": "workable", "name": "Workable", "category": "HR & Recruiting", "description": "Job board syndication, AI candidate screening, and candidate communication", "action_count": 38},
    {"id": "recruitee", "name": "Recruitee", "category": "HR & Recruiting", "description": "Collaborative hiring platform, candidate pipelines, and automated recruiting emails", "action_count": 32},
    {"id": "breezyhr", "name": "Breezy HR", "category": "HR & Recruiting", "description": "Visual candidate recruiting pipelines, video interviews, and team scorecards", "action_count": 30},
    {"id": "jazzhr", "name": "JazzHR", "category": "HR & Recruiting", "description": "Affordable applicant tracking system for fast-growing businesses", "action_count": 28},
    {"id": "smartrecruiters", "name": "SmartRecruiters", "category": "HR & Recruiting", "description": "Enterprise talent acquisition suite, CRM candidate sourcing, and offer management", "action_count": 45},
    {"id": "jobvite", "name": "Jobvite", "category": "HR & Recruiting", "description": "End-to-end recruitment marketing, applicant tracking, and employee onboarding", "action_count": 35},
    {"id": "bullhorn", "name": "Bullhorn CRM", "category": "HR & Recruiting", "description": "Staffing and recruiting CRM, candidate resume parsing, and placement tracking", "action_count": 40},
    {"id": "personio", "name": "Personio", "category": "HR & Recruiting", "description": "European HR software for small and medium-sized enterprises and recruiting", "action_count": 38},
    {"id": "hibob", "name": "HiBob (Bob)", "category": "HR & Recruiting", "description": "Modern HR platform for dynamic workplace culture and people management", "action_count": 34},
    {"id": "lattice", "name": "Lattice", "category": "HR & Recruiting", "description": "Employee performance management, 1-on-1 agendas, OKRs, and employee engagement", "action_count": 32},
    {"id": "culture-amp", "name": "Culture Amp", "category": "HR & Recruiting", "description": "Employee engagement surveys, performance reviews, and people analytics", "action_count": 26},
    {"id": "gem", "name": "Gem", "category": "HR & Recruiting", "description": "Talent engagement, sourcing sequences, talent CRM, and pipeline analytics", "action_count": 30},
    {"id": "checkr", "name": "Checkr", "category": "HR & Recruiting", "description": "Automated background check screening, identity verification, and compliance", "action_count": 24},
    {"id": "seekout", "name": "SeekOut", "category": "HR & Recruiting", "description": "AI-powered talent search, diversity sourcing, and candidate contact enrichment", "action_count": 26},
    {"id": "15five", "name": "15Five", "category": "HR & Recruiting", "description": "Continuous performance management, weekly check-ins, and high performance culture", "action_count": 22},
    {"id": "leapsome", "name": "Leapsome", "category": "HR & Recruiting", "description": "People enablement platform for continuous feedback, goal setting, and appraisals", "action_count": 24},
    {"id": "charthop", "name": "ChartHop", "category": "HR & Recruiting", "description": "People analytics, headcount planning, compensation reviews, and org charting", "action_count": 28},
    {"id": "factorial", "name": "Factorial HR", "category": "HR & Recruiting", "description": "All-in-one HR software for time tracking, document management, and payroll", "action_count": 26},
    {"id": "teamtailor", "name": "Teamtailor", "category": "HR & Recruiting", "description": "Modern ATS with career site building, candidate NPS, and candidate nurture", "action_count": 32},
    {"id": "pinpointhq", "name": "Pinpoint ATS", "category": "HR & Recruiting", "description": "Intelligent talent acquisition software designed to attract top candidates", "action_count": 25},
    {"id": "hireology", "name": "Hireology", "category": "HR & Recruiting", "description": "Recruitment CRM and candidate verification for multi-location businesses", "action_count": 22},
    {"id": "fountain", "name": "Fountain", "category": "HR & Recruiting", "description": "High-volume frontline workforce hiring and applicant workflow automation", "action_count": 28},
    {"id": "comeet", "name": "Comeet ATS", "category": "HR & Recruiting", "description": "Collaborative recruitment platform with integrated sourcing and screening", "action_count": 24},

    # ──────────────────────────────────────────────────────────────────────────
    # 8. EXTENDED ENTERPRISE PLATFORMS & CLOUD INFRASTRUCTURE
    # ──────────────────────────────────────────────────────────────────────────
    {"id": "perplexity", "name": "Perplexity AI", "category": "AI & Data", "description": "Real-time web research, citations, and factual intelligence synthesis", "action_count": 24},
    {"id": "replicate", "name": "Replicate", "category": "AI & Data", "description": "Run open-source machine learning models in the cloud with API endpoints", "action_count": 36},
    {"id": "cohere", "name": "Cohere", "category": "AI & Data", "description": "Enterprise language models, rerankers, and multi-lingual representation", "action_count": 30},
    {"id": "langchain", "name": "LangChain Hub", "category": "AI & Data", "description": "Browse and run prompt chains, agents, and custom output parsers", "action_count": 20},
    {"id": "llamaindex", "name": "LlamaIndex", "category": "AI & Data", "description": "Data framework for connecting custom data sources to large language models", "action_count": 22},
    {"id": "weights-biases", "name": "Weights & Biases", "category": "AI & Data", "description": "MLOps experiment tracking, dataset versioning, and model registry", "action_count": 32},
    {"id": "mlflow", "name": "MLflow", "category": "AI & Data", "description": "Open source platform for the complete machine learning lifecycle", "action_count": 28},
    {"id": "motherduck", "name": "MotherDuck", "category": "AI & Data", "description": "Cloud analytics platform powered by DuckDB for serverless analytical queries", "action_count": 20},
    {"id": "tableau", "name": "Tableau", "category": "AI & Data", "description": "Interactive data visualization, enterprise dashboards, and BI reporting", "action_count": 38},
    {"id": "powerbi", "name": "Microsoft Power BI", "category": "AI & Data", "description": "Business analytics service providing interactive visualizations and business BI", "action_count": 42},
    {"id": "looker", "name": "Google Looker", "category": "AI & Data", "description": "Modern enterprise platform for business intelligence and data analytics", "action_count": 36},
    {"id": "metabase", "name": "Metabase", "category": "AI & Data", "description": "Open source business intelligence tool for fast SQL queries and charts", "action_count": 26},
    {"id": "hex", "name": "Hex Data Platform", "category": "AI & Data", "description": "Collaborative analytics platform combining SQL, Python, and interactive apps", "action_count": 24},
    {"id": "dbt", "name": "dbt Cloud", "category": "AI & Data", "description": "Data transformation workflow orchestration, testing, and documentation", "action_count": 34},
    {"id": "airbyte", "name": "Airbyte", "category": "AI & Data", "description": "ELT data integration platform for synchronizing cloud SaaS data warehouses", "action_count": 30},
    {"id": "fivetran", "name": "Fivetran", "category": "AI & Data", "description": "Automated data movement platform with zero-maintenance pipelines", "action_count": 32},
    {"id": "terraform", "name": "HashiCorp Terraform", "category": "Engineering", "description": "Infrastructure as Code to provision cloud resources across any provider", "action_count": 40},
    {"id": "pulumi", "name": "Pulumi", "category": "Engineering", "description": "Modern Infrastructure as Code using real programming languages", "action_count": 34},
    {"id": "docker-hub", "name": "Docker Hub", "category": "Engineering", "description": "Container image repository, build automation, and registry management", "action_count": 28},
    {"id": "kubernetes", "name": "Kubernetes", "category": "Engineering", "description": "Automated deployment, scaling, and management of containerized applications", "action_count": 52},
    {"id": "cloudflare", "name": "Cloudflare", "category": "Engineering", "description": "DNS management, edge workers, SSL certificates, and zero-trust security", "action_count": 46},
    {"id": "postman", "name": "Postman", "category": "Engineering", "description": "API platform for building, testing, and managing team API collections", "action_count": 35},
    {"id": "render-cloud", "name": "Render Cloud", "category": "Engineering", "description": "Unified cloud to build and run web services, static sites, and databases", "action_count": 28},
    {"id": "flyio", "name": "Fly.io", "category": "Engineering", "description": "Deploy app servers close to users worldwide with global microVMs", "action_count": 26},
    {"id": "railway", "name": "Railway.app", "category": "Engineering", "description": "Instant cloud deployments, managed databases, and microservice infrastructure", "action_count": 25},
    {"id": "mattermost", "name": "Mattermost", "category": "Communication", "description": "Secure, open-source collaboration platform for technical and operational teams", "action_count": 36},
    {"id": "twilio-sms", "name": "Twilio SMS", "category": "Communication", "description": "Global programmatic SMS text messaging, verification codes, and phone calls", "action_count": 34},
    {"id": "sendgrid", "name": "SendGrid", "category": "Communication", "description": "Cloud-based customer communication platform for transactional and marketing email", "action_count": 40},
    {"id": "postmark", "name": "Postmark", "category": "Communication", "description": "Lightning-fast transactional email delivery and inbound parse webhook processing", "action_count": 28},
    {"id": "resend", "name": "Resend", "category": "Communication", "description": "Developer-first email platform for building, testing, and delivering modern emails", "action_count": 26},
    {"id": "customerio", "name": "Customer.io", "category": "Communication", "description": "Automated messaging platform for sending personalized customer lifecycle emails", "action_count": 32},
    {"id": "braze", "name": "Braze", "category": "Communication", "description": "Comprehensive customer engagement platform for cross-channel customer journeys", "action_count": 38},
    {"id": "iterable", "name": "Iterable", "category": "Communication", "description": "Cross-channel marketing platform powering unified customer communications", "action_count": 34},
    {"id": "onesignal", "name": "OneSignal", "category": "Communication", "description": "Omnichannel customer engagement with mobile and web push notifications", "action_count": 30},
    {"id": "brevo", "name": "Brevo (Sendinblue)", "category": "Communication", "description": "All-in-one marketing platform for email campaigns, SMS, and WhatsApp chats", "action_count": 32},

    # ──────────────────────────────────────────────────────────────────────────
    # 9. SALES INTELLIGENCE, MEETING RECORDING & PRODUCTIVITY
    # ──────────────────────────────────────────────────────────────────────────
    {"id": "apollo", "name": "Apollo.io", "category": "Sales", "description": "B2B lead intelligence, contact enrichment, and multi-step sales sequences", "action_count": 48},
    {"id": "zoominfo", "name": "ZoomInfo", "category": "Sales", "description": "Enterprise go-to-market intelligence, company data, and buyer intent signals", "action_count": 42},
    {"id": "clearbit", "name": "Clearbit", "category": "Sales", "description": "Real-time B2B data enrichment, IP reveal, and company domain lookup", "action_count": 36},
    {"id": "clay", "name": "Clay", "category": "Sales", "description": "Automate outbound prospecting by pulling data from 50+ data providers", "action_count": 34},
    {"id": "hunter", "name": "Hunter.io", "category": "Sales", "description": "Find professional email addresses and verify deliverability in seconds", "action_count": 28},
    {"id": "lemlist", "name": "Lemlist", "category": "Sales", "description": "Personalized cold outreach campaigns with automated follow-ups and deliverability", "action_count": 32},
    {"id": "instantly", "name": "Instantly.ai", "category": "Sales", "description": "Scale email outreach with unlimited accounts, warm-up, and AI lead finder", "action_count": 30},
    {"id": "gong", "name": "Gong.io", "category": "Sales", "description": "Revenue intelligence platform capturing sales calls, deal risks, and coaching", "action_count": 38},
    {"id": "attio", "name": "Attio", "category": "Sales", "description": "The next-generation CRM built for modern teams with dynamic relationship graphs", "action_count": 35},
    {"id": "folk", "name": "Folk CRM", "category": "Sales", "description": "All-in-one CRM for managing candidate, investor, and client relationships", "action_count": 28},
    {"id": "highspot", "name": "Highspot", "category": "Sales", "description": "Sales enablement platform connecting content, guidance, and pitch analytics", "action_count": 30},
    {"id": "seismic", "name": "Seismic", "category": "Sales", "description": "Global leader in sales enablement, automated content personalization, and training", "action_count": 34},
    {"id": "superhuman", "name": "Superhuman", "category": "Productivity", "description": "The fastest email experience ever made with split inboxes and triage shortcuts", "action_count": 24},
    {"id": "loom", "name": "Loom", "category": "Productivity", "description": "Async video messaging, screen recordings, transcripts, and AI summaries", "action_count": 28},
    {"id": "grain", "name": "Grain.com", "category": "Productivity", "description": "AI meeting recorder that transcribes, clips, and summarizes customer calls", "action_count": 26},
    {"id": "fathom", "name": "Fathom", "category": "Productivity", "description": "Free AI meeting recorder that records, transcribes, and summarizes Zoom/Meet calls", "action_count": 24},
    {"id": "otter", "name": "Otter.ai", "category": "Productivity", "description": "AI-powered real-time transcription, meeting notes, and automated team summaries", "action_count": 30},
    {"id": "linearb", "name": "LinearB", "category": "Engineering", "description": "Software delivery intelligence platform for tracking engineering cycle times and DORA metrics", "action_count": 28},
]

