apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaeloom
bases:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: .*
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: LOG_LEVEL
          value: info
      - op: add
        path: /spec/template/spec/containers/0/resources/requests
        value:
          cpu: "500m"
          memory: "1Gi"
