apiVersion: v1
kind: Service
metadata:
  name: vaeloom-search-service
  namespace: vaeloom
  labels:
    app.kubernetes.io/name: search-service
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 3050
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: search-service
