apiVersion: v1
kind: Service
metadata:
  name: vaeloom-rbac-service
  namespace: vaeloom
  labels:
    app.kubernetes.io/name: rbac-service
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 3170
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: rbac-service
