apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaeloom-ingress
  namespace: vaeloom
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  tls:
    - hosts:
        - vaeloom.dev
        - api.vaeloom.dev
      secretName: vaeloom-tls
  rules:
    - host: vaeloom.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vaeloom-web
                port:
                  number: 3000
    - host: api.vaeloom.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vaeloom-api
                port:
                  number: 4000
